### ISSUE TITLE
Permit Number Field Invisible on iPhone 5C, vertical orientation 

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#10]
Screengrab/videos (insert file names here)
Permit Number Field Invisible on iPhone 5C, vertical orientation (1)
Permit Number Field Invisible on iPhone 5C, vertical orientation (2)
Permit Number Field Invisible on iPhone 5C, vertical orientation (3)

Link
https://permit-finder.digital-staging.boston.gov/

 Environment
(Device > OS > Browser)
iPhone 5C > iOS 10.3.3 > Safari

Section
(Page > Area > Element)
Permit Finder > Permit Number Entry Field

Brief Description
Using the vertical orientation, the permit number entry field is severely truncated [see Permit Number Field Invisible on iPhone 5C, vertical orientation (1)]; the passive phrase “Permit number” is not displayed. When the user enters text, the characters are invisible [see Permit Number Field Invisible on iPhone 5C, vertical orientation (2)]. However, changing to horizontal orientation reveals the characters entered this way, and under that orientation the field is fully functional [see Permit Number Field Invisible on iPhone 5C, vertical orientation (3)]. This issue could not be reproduced on newer iPhones or iPads.
NOTE: Very similar issues have been found on other mobile devices: a Samsung G8 running Android 8.0.0, an LG6 running Android 6.0, and a Samsung Android Mini running Android 6.0.1, all of these devices running Chrome (it's likely a great many other devices are affected). In the case of the G8, when the device is rotated horizontally, the on-screen keyboard completely obscures the permit number text field.

 Steps to reproduce
1. Go to the Permit Finder (staging) site, maintaining vertical orientation
2. Select the number entry field and enter some text

Desired Result
All text entered is visible, functionality unimpaired.

Actual Result
The user can enter text, but cannot see the characters he has entered.

![Permit Number Field Invisible on iPhone 5C, vertical orientation (1)](https://user-images.githubusercontent.com/49662945/62144812-6b967c00-b2c0-11e9-892c-4d96454f995a.PNG)
![Permit Number Field Invisible on iPhone 5C, vertical orientation (2)](https://user-images.githubusercontent.com/49662945/62144813-6b967c00-b2c0-11e9-9e5d-247af154a807.PNG)
![Permit Number Field Invisible on iPhone 5C, vertical orientation (3)](https://user-images.githubusercontent.com/49662945/62144814-6b967c00-b2c0-11e9-96d5-5bfbc1048679.PNG)

**Comment by reillyzlab** [comment]
This is not just exclusive to iPhone 5. This is due to a breakpoint. 

As seen in on iPhone X:
![IMG_C4A37DB3E118-1](https://user-images.githubusercontent.com/20731897/71523845-c85e8880-2898-11ea-9095-b5e0e3005085.jpeg)

Search bar should stretch the length of the screen with the search button below the search bar. 

See Sebastian if you need additional design guidance.

**Comment by phillipbentonkelly** [comment]
I created a fix and its now on [Staging](https://permit-finder.digital-staging.boston.gov/permit)

**Comment by reillyzlab** [comment]
![IMG_4390](https://user-images.githubusercontent.com/20731897/81720626-a8e18a00-944c-11ea-878d-c1694e2647e1.png)

Also found by Reilly on iphone x on 5-12-20

**Comment by phillipbentonkelly** [comment]
Updated UI: removed padding, used smaller font, and used '#' instead of 'number'. The full word 'Permit Number' doesn't fit at smaller devices, and shrinking the font even more in those aspect ratios doesn't look good.

https://permit-finder.digital-staging.boston.gov/

**Comment by paylakatel** [comment]
This looks good on staging - we can move to production. Thank you!

**Comment by phillipbentonkelly** [comment]
Deployed, Live; Leaving the ticket un-closed until Monday

**Comment by paylakatel** [comment]
Looks good on prod!
