### ISSUE TITLE
The last button in the Get Started Section for the Visiting Boston page on the Drupal 8 pages does not have any content

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#100]
Screengrab/videos (insert file names here)
2019 09 13, The last button in the Get Started section has no content on the Drupal 8 page.mp4
[2019 09 13, The last button in the Get Started section has no content on the Drupal 8 page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3610806/2019.09.13.The.last.button.in.the.Get.Started.section.has.no.content.on.the.Drupal.8.page.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/visiting-boston

Dupral 7 Link:
•	https://www.boston.gov/visiting-boston

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Tablet (Android Ellipses)  > Android 7.0 > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Get Started section > Button Icons

Brief Description
The last button in the Get Started Section for the Visiting Boston page on the Drupal 8 pages does not have any content

Steps to reproduce
1. Go to the Visiting Boston page for Drupal 7 and Drupal 8
2. Go to the Get Started Section 

Desired Result
•	Both pages have the proper content for the section

Actual Result
•	The last button for the Get Started section for the Drupal 8 page has no content

**Comment by reillyzlab** [comment]
Resolved so closing
