### ISSUE TITLE
The Fitness Class Descriptions Section has a missing image on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#101]
Screengrab/videos (insert file names here)
2019 09 13, Parks Summer Fitness Content Missing.mp4
[2019 09 13, Parks Summer Fitness Content Missing.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3611098/2019.09.13.Parks.Summer.Fitness.Content.Missing.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/departments/parks-and-recreation/boston-parks-summer-fitness-series 

Dupral 7 Link:
•	https://www.boston.gov/departments/parks-and-recreation/boston-parks-summer-fitness-series

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Tablet (Android Ellipses)  > Android 7.0 > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Get Started section > Button Icons

Brief Description
The Fitness Class Descriptions Section has a missing image on the Drupal 8 page

Steps to reproduce
1. Go to the Boston Parks Summer Fitness Series page for Drupal 7 and Drupal 8
2. Go to the Weekly Schedule section 

Desired Result
•	Both pages have the proper content for the section

Actual Result
•	The Fitness Class Descriptions Section is missing an image

**Comment by reillyzlab** [comment]
Resolved so closing
