### ISSUE TITLE
The contact information for the completed permit numbers do not match the information in the verification sheet - "Completed" State

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#11]
Screengrab/videos (insert file names here)
2019 07 30, Completed Contact Into does not agree with source.mp4
[2019 07 30, Completed Contact Into does not agree with source.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3452859/2019.07.30.Completed.Contact.Into.does.not.agree.with.source.mp4.zip)

Link
https://permit-finder.digital-staging.boston.gov/

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Permit Information > Contact Us > Contact Information

Brief Description
The contact information for the completed permit numbers do not match the information in the verification sheet

Steps to reproduce
1. Go to permit-finder staging site
2. Check contact information for permits in a “completed” state: (BFDF681680, CHM914347, SMK911643)

Desired Result

- Contact information matches the information in the validation source
-        Validation string is “Call 617-343-3628.”

Actual Result
- Contact information does not match the information in the validation source
-       Return string is “Call the Boston Fire Department at (617) 343-3628.”

**Comment by paylakatel** [comment]
Okay because the new version is more descriptive and still correct.
