### ISSUE TITLE
Test 9, Links on home page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#110]
Screengrab/videos (insert file names here)
2020 03 23, Test 9, Links on home page
[2020 03 23, Test 9, Links on home page, Low Res.mov.zip](https://github.com/CityOfBoston/Iterators/files/4378189/2020.03.23.Test.9.Links.on.home.page.Low.Res.mov.zip)

.mp4

Link
https://d8-stg.boston.gov/

Node # (if known)
Node 21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Safari

Trusted Tester Test
9 Links & Buttons

Brief Description
Accessible links needed on home page

Steps to reproduce
1)	00:00, Start at the link
2)	00:04, Turn on the ANDI utility and switch to “Links and Buttons”
3)	00:10, Look at the first category of link issues
a)	00:16 - 00:22, The links in the Latest News section do not have accessible information
4)	00:28, Look at the second category of link issues
a)	00:28 – 00:50, This section lists several links with miscellaneous alerts that the links are not formatted with accessibility information.  ANDI is not able to display the specific links on the page.
5)	00:53 – 01:05
a)	01:03:  Note a small pink dot that is highlighted.  This may be a placeholder for an invisible link.  The recommendation is to use “id” tags for anchor locations
6)	01:10 – 01:30
a)	Several links are not listed in the tab order.  ANDI is again not able to show the links on the page.

Desired Result
All links have accessible information.

Actual Result
Links do not have accessible information, or need an updated link format.

**Comment by subaha-cob** [comment]
Trouble finding links. I am not sure that I will completely fix all the hidden links/<a> tags in this round. As it stands we need to test all the article and landing pages because they are the most affected. I don't want to introduce more bugs.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
This was verified on UAT but has an ambiguous link, which is the same accessibility text but pointing to different URLs. This is only staging information and will need to be retested on the final site with actual information.
