### ISSUE TITLE
Hamburger menu is out of sync when keyboard is used to tab through menu items and then shift+tab is used to move back to main content

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#116]
Screengrab/videos (insert file names here)
Keyboard, Home page, Menu becomes out of sync.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Chrome 83

Trusted Tester Test
Keyboard

Brief Description
Menu display becomes out of sync with some keyboard actions

Steps to reproduce
1)	00:00, Click in the URL field and start pressing the tab key until the focus enters the main page
2)	00:09, The tab key brings the focus into the main page
3)	00:13, Continue pressing the tab key to go through the menu items until the link is on the #content anchor.
4)	00:15, Press the Return key
a)	BUG:  The menu becomes out of sync
5)	00:18, Refresh the page to reset it back to normal
6)	00:28, Reproduce the bug by tabbing to the #content anchor link
7)	00:29, Press the return key
a)	BUG:  The bug is reproducible

Desired Result
Menu display is open or closed

Actual Result
Menu display becomes out of sync on some keyboard actions

[Keyboard, Home page, Menu becomes out of sync.zip](https://github.com/CityOfBoston/Iterators/files/4983942/Keyboard.Home.page.Menu.becomes.out.of.sync.zip)

**Comment by subaha-cob** [comment]
I still need to test this properly. We also need to test other sites using out menu.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
This is fixed and verified on UAT with  https://d8-uat.boston.gov/ on Chrome Incognito.
