### ISSUE TITLE
Contact Us Form gives duplicate error message if Signup button is pressed twice with invalid values in both fields 

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#119]
Screengrab/videos (insert file names here)
Functional, Home Page, Contact Us Form.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Chrome 83

Trusted Tester Test
N/A --- Functional Bug

Brief Description
Error message for Stay Connected form

Steps to reproduce
1)	00:00, Scroll down to the Stay Connected form
2)	00:05, Enter invalid information into both fields.
3)	00:06, Click on the Signup button.
a)	Note, error messages are displayed as expected.
4)	00:08, Click on the Signup button a second time
**a)	BUG:  A duplicate error message is displayed for the zip code**
5)	00:18, Enter a valid email address and leave the invalid zip code 
6)	00:24, Click on Signup and the error messages stay, as expected.
7)	00:44, Remove the zipcode so that it is blank
8)	00:45, Click on the Signup button
a)	BUG:  The form is submitted even though there are error messages for the zipcode (See #120)

Desired Result
Error Messages match the response.

Actual Result
Error messages are not consistent with the form
[Functional, Home Page, Contact Us Form.zip](https://github.com/CityOfBoston/Iterators/files/4985527/Functional.Home.Page.Contact.Us.Form.zip)

**Comment by andrebtlima** [comment]
Contact Us Form gives duplicate error message if Signup button is pressed twice with invalid values in both fields.

**Comment by subaha-cob** [comment]
Fixed. We need to test on other sites using this form. the regression test will help fish out any new bugs we introduced. I think the .asp pages Rich S. deploys need to be test. Can you add the links to his websites he manages.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
The first bug on line 4 at 8 seconds is fixed. The second bug, at line 8 at 45 seconds is still present. The form will submit with an empty ZIP code. This was testing on https://d8-uat.boston.gov/ using Chrome in Ingognito.

**Comment by subaha-cob** [comment]
@jill-iterators I believe validation was just for the email address only. The zipcode is not required. We can discuss if we want validation added for the zipcode with the rest of the Digital team. But for now this is functioning as designed. please take note @andrebtlima

**Comment by ollie-iterators** [comment]
This appears to be fixed
