### ISSUE TITLE
Contact Us Form can be submitted with blank zipcode despite error message 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/Iterators#120]
Screengrab/videos (insert file names here)
Functional, Home Page, Contact Us Form.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Chrome 83

Trusted Tester Test
N/A --- Functional Bug

Brief Description
Error message for Stay Connected form

Steps to reproduce
1)	00:00, Scroll down to the Stay Connected form
2)	00:05, Enter invalid information into both fields.
3)	00:06, Click on the Signup button.
a)	Note, error messages are displayed as expected.
4)	00:08, Click on the Signup button a second time
a)	BUG:  A duplicate error message is displayed for the zip code (See #119)
5)	00:18, Enter a valid email address and leave the invalid zip code 
6)	00:24, Click on Signup and the error messages stay, as expected.
7)	00:44, Remove the zipcode so that it is blank
8)	00:45, Click on the Signup button
**a)	BUG:  The form is submitted even though there are error messages for the zipcode**

Desired Result
Error Messages match the response.

Actual Result
Error messages are not consistent with the form
[Functional, Home Page, Contact Us Form.zip](https://github.com/CityOfBoston/Iterators/files/4985527/Functional.Home.Page.Contact.Us.Form.zip)

**Comment by subaha-cob** [comment]
Yes, contact us zip code is not required, therefore it can be submitted without zip code.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/
