### ISSUE TITLE
Forms, Home Page, Linked information

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#122]
Screengrab/videos (insert file names here)
Forms, Home Page, Linked information
[Forms, Home Page, Linked information.zip](https://github.com/CityOfBoston/Iterators/files/5035209/Forms.Home.Page.Linked.information.zip)
<img width="1516" alt="Forms, Home Page, Linked information" src="https://user-images.githubusercontent.com/33845414/89540333-e3985b80-d7ca-11ea-8f22-d00c4b3abcee.png">

.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Safari

Trusted Tester Test
Forms

Brief Description
Form instructions are not linked to the field

Steps to reproduce
1)	00:00, Go to the link and scroll down to the Stay Connected form
2)	00:04, Activate an accessibility tool to display the Form information
3)	00:05, Note that the accessibility information is not complete for the email and zip code fields

Desired Result
All information that is available to a user should also be available programmatically for all form fields.

Actual Result
Form fields do not have accessibility information linked to them.

**Comment by subaha-cob** [comment]
This is all set now.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@david-iterators  what accessibility tool are you using to test these? I think it would be helpful for me in my own testing, provided it'd free to download/install

**Comment by subaha-cob** [comment]
@jill-iterators this is on the live site. So please test there unless I say otherwise. Thanks.

**Comment by ollie-iterators** [comment]
This appears to be fixed
