### ISSUE TITLE
Keyboard, Scrolling Freezes after menu access

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#125]
Screengrab/videos (insert file names here)
Keyboard, Scrolling Freezes after menu access.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Safari

Trusted Tester Test
Keyboard

Brief Description
The window will not scroll after a specific keyboard sequence occurs

Steps to reproduce
1)	00:00, Go to the link
2)	00:02, Scroll the window up and down in order to demonstrate that this is working now.
3)	00:10, Use the keyboard to go to the menu on the left hand side of the window.
4)	00:12, Close the menu using the mouse to click on the close button
5)	00:14, BUG:  Try to scroll the window up and down, but that is no longer working after this sequence.
6)	00:20, Click on the browser refresh window to reload the page.
7)	00:28, Note that the window can scroll up and down again.
8)	00:38, Repeat the sequence of events as before
9)	00:40, BUG:  Note that the bug is reproducible and the window will not scroll up and down.

Desired Result
Window can scroll at any time

Actual Result
Window will not scroll after a specific sequence of events.

**Comment by subaha-cob** [comment]
I am struggling with this bug. Still trying to figure out what is causing this.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob I just tested this on staging and having trouble reproducing the freezing issue. Both staging and UAT seem to be working but obviously UAT has your fix Stella which I think makes the keyboard interaction with the hamburger menu more intuitive.

**Comment by david-iterators** [comment]
Verified on UAT.
