### ISSUE TITLE
Description Info for the Completed Permits do not match the information in the verification document

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#13]
Screengrab/videos (insert file names here)
2019 07 30, Completed Permits Description does not match the validation data.mp4
[2019 07 30, Completed Permits Description does not match the validation data.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3458308/2019.07.30.Completed.Permits.Description.does.not.match.the.validation.data.mp4.zip)

Link
https://permit-finder.digital-staging.boston.gov/

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 76

Section
(Page > Area > Element)
Permit Page > Permit Information > Description Info

Brief Description
Description Info for the Completed Permits do not match the information in the verification document

Steps to reproduce
1. Go to the permit finder page
2. Search for all the permits that are labeled as completed (A939804, BFDF681680, CHM914347, SMK911643)
3. Check out the description section

Desired Result
•	The description information matches the verification data

Actual Result
•	The description information does not match the verification data

**Comment by reillyzlab** [comment]
@paylakatel and @sebastianebarb to advise @phillipbentonkelly on how to implement this in the revised interface
