### ISSUE TITLE
All visual lists are not programmatically identified by what type of list they are

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#134]
Screengrab/videos (insert file names here)
2020 08 20, List not found in Mayor Article Page.mp4
[2020 08 20, List not found in Mayor Article Page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5104799/2020.08.20.List.not.found.in.Mayor.Article.Page.mp4.zip)

Link
https://d8-stg.boston.gov/calendar/mayor-main-trolley-tour-day-3

Node # (if known)
45361

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Firefox 79

Trusted Tester Test
Content Structure Lists

Brief Description
All visual lists are not programmatically identified by what type of list they are

Steps to reproduce
1)	Go to the Mayor article page
2)	00:06 – The text in the Neighborhood section of the information area on the article is not identified as a list despite it having the visual appearance of a list.

Desired Result
•	All visual lists are programmatically identified by what type of list they are

Actual Result
•	The list in the Neighborhood section of the information area of the article is not identified as a list

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
This looks good now, the issue has been fixed
