### ISSUE TITLE
 Synchronized Media Accessibility Issues

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#136]
Screengrab/videos (insert file names here)
2020 08 21, Synchronized Media Accessibility Issues.mp4

Link
https://d8-stg.boston.gov/civic-engagement/love-your-block

Node # (if known)
2861

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Chrome 84

Trusted Tester Test
17) Synchronized media

Brief Description
The videos on the Love Your Block article page do not have the Accessibility features needed for Synchronized media

Steps to reproduce
1)	Go to the “Love Your Block article” and find the video on the page
2)	00:00 Check out the features that are available for the video and compare it to the features that are needed for the video to be Accessible, such as Caption buttons and Audio Description buttons. 
[2020 08 21, Synchronized Media Accessibility Issues.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5110611/2020.08.21.Synchronized.Media.Accessibility.Issues.mp4.zip)

Desired Result
•	The videos on the page have all the required features for the synchronized media to be accessible

Actual Result
•	The videos on the page do not have: Captions buttons and Audio Description buttons
o	A start to fixing the issue of having an accessible synchronized media video would be to add an accessible transcript of the synchronized media video.

**Comment by subaha-cob** [comment]
@andrebtlima this will be a little involved because I will need to edit the videos if the Youtube captions are not good. Either way i will need accessible to the city's Youtube account. Or we can assign to someone else like the content editor or digital story tellers. At least some that knows how to work Youtube editing tools.

**Comment by subaha-cob** [comment]
@ollie-iterators same as this issue: https://github.com/CityOfBoston/Iterators/issues/137 or is this something different?

**Comment by subaha-cob** [comment]
@andrebtlima same as issue: https://github.com/CityOfBoston/Iterators/issues/137

**Comment by andrebtlima** [comment]
Closing because this is duplicative of #137
