### ISSUE TITLE
Accessibility Summary for Permit Finder

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#14]
Attached is the VPAT document that summarizes the testing completed for Permit Finder.  This document references more detailed bug reports for individual items.  Note that we should discuss the VPAT and this testing in more detail.

[VPAT2.3RevWCAG, City of Boston, Permit Finder.docx](https://github.com/CityOfBoston/Iterators/files/3467617/VPAT2.3RevWCAG.City.of.Boston.Permit.Finder.docx)

**Comment by reillyzlab** [comment]
This is simply a summary of individual items that were reported as individual tickets. Closing, but @jfalvey and @andrebtlima you should look through if you haven't already as an example of what they would probably do for boston.gov.
