### ISSUE TITLE
Functional, Search error with empty string

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#140]
Screengrab/videos (insert file names here)
2020 08 18, Functional, Search error with empty string.mp4

Link
https://d8-stg.boston.gov

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS > Chrome 84

Trusted Tester Test
N/A

Brief Description

Steps to reproduce
1)	00:00, Load the page
2)	00:03, Click on the Search icon
3)	00:05, Enter “Test” for the search and **note**:  this will work correctly
4)	00:09, Remove the search string the click on the search icon.
a)	BUG:  The search results in an error message
[2020 08 18, Functional, Search error with empty string.zip](https://github.com/CityOfBoston/Iterators/files/5138565/2020.08.18.Functional.Search.error.with.empty.string.zip)

Desired Result
Search function does not result in an error.

Actual Result
Error message with empty search string

**Comment by subaha-cob** [comment]
Real bug. Looking into this tomorrow with David. Should have been a Drupal ticket.

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
This is now working as expected. Will close.
