### ISSUE TITLE
Link Displays Incorrectly at Certain Window Sizes.mp4

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#142]
Screengrab/videos (insert file names here)
2020 08 24, Link Displays Incorrectly at Certain Window Sizes.mp4
[Link Displays Incorrectly at Certain Window Sizes.mp4.zip]

Link
https://d8-stg.boston.gov/departments/emergency-medical-services/cpr-training

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Mac OS 10.15.5 > Chrome 84

Trusted Tester Test
n/a

Brief Description
There is a responsive error due to the size of the window, causing the link to display improperly.

Steps to reproduce
1)	00:00, Go to the link listed above
2)	00:06, See link and note that the “g” of the link wraps to a second line. 
Note... This is a bug as it should split in a logical place if it must split at all.
3)	10:00, Starting to reduce the size of the window. 
4)	00:18, Go to the same link and note at the reduced size, the link is visually correct
5)	00:23, Expand the window again and go back to original error to contrast the difference. 
a)	This is a functional bug, not an Accessibility bug.

Desired Result
Able to view all links on the website without a singular letter wrapping to another line 

Actual Result
Unable to view all links on the website without a singular letter wrapping to another line

**Comment by jill-iterators** [comment]
The attached link also displays the email  incorrectly under the Need to Know section: https://d8-stg.boston.gov/departments/emergency-medical-services/cpr-training

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by jill-iterators** [comment]
Verified on UAT.
