### ISSUE TITLE
There are images on the page that are incorrectly labeled as background images.

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#148]
Screengrab/videos (insert file names here)
2020 08 20, Background Image Errors.mp4
[2020 08 20, Background Image Errors.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5124330/2020.08.20.Background.Image.Errors.mp4.zip)

Link
https://d8-stg.boston.gov/calendar/mayor-main-trolley-tour-day-3

Node # (if known)
45361

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Firefox 79

Trusted Tester Test
Images

Brief Description
There are images on the page that are incorrectly labeled as background images.

Steps to reproduce
1)	Go to the page on the site
2)	00:00 The images in the Information area are said to be background images, despite them describing the text that is next to them which means that they are not purely decorative images. The image of text describing the article also is not a decorative image, and should not be an image. The links in the "Mayor on Main Events" section area area are also not background images and they have alt-text which, even if they were supposed to be background images, would make them have errors as background images should not have alt-text. Finally, the icon on the footer should not be a background image because it is linked to a link on the page, and should not be a background image because of that.

Desired Result
•	All background images are not necessary for information to be displayed

Actual Result
•	The clock image, the location image, phone image, text description of article, buttons in the Mayor on Main section on the page and the “Bos: 311” image on the footer are incorrectly said to be background images

**Comment by subaha-cob** [comment]
@jill-iterators I am not sure why you think they are not background images because they are. We can chat through some of this tickets in our next meeting. @andrebtlima please take note.

**Comment by jill-iterators** [comment]
@subaha-cob I have added information to clarify the issue, the images should not be background images, rather, they are descriptive images. When we tested they looked to be background images. Sorry for any confusion. Detail is below:

I made a new video which is shown below: (2020 09 06, Background Images are incorrectly labeled as Background Images.mp4)
[2020 09 06, Background Images are incorrectly labeled as Background Images.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5180206/2020.09.06.Background.Images.are.incorrectly.labeled.as.Background.Images.mp4.zip)

1. 00:05 - Show the background images on the page
2. 00:07 - Hide background images. Note that the information in the page goes down when the image above the title becomes invisible. This means that it is not a background image, and is an informative image about the event.
3. 00:39 - The images in the footer area (The City of Boston Logo and the Bos: 311 image are said to be background images). When they are made hidden, information is lost from the site. Logos on the page are never background images, and the Bos: 311 image is on a link which would not be able to be seen if the image became invisible. That means that those two images are not background images.

**Comment by subaha-cob** [comment]
@jill-iterators Got it. this makes sense now 👍

**Comment by david-iterators** [comment]
Hi @subaha-cob  and @mmcgowanBOS   Please see the attached screenshot.  This was tested at https://d8-uat.boston.gov/ and also at https://boston.gov   There are meaningful images that are present in the background and background images may not be processed by all assistive technologies.  Please let us know if you have additional questions about this.

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/33845414/113581975-d64f9d00-95f5-11eb-89d3-832868eb4a55.png">

**Comment by subaha-cob** [comment]
@david-iterators We have decided that this are all decorative. Some of them completely disappear in mobile view. Not worth the time and effort needed to change the layout of the website to fix the issue.

**Comment by ollie-iterators** [comment]
This issue has been resolved.
