### ISSUE TITLE
 Form not in Sync with Blue Line Representing Completion.mp4

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#158]
Screengrab/videos (insert file names here)
Form not in Sync with Blue Line Representing Completion.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention?step=reviewRequest

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.5 > Chrome 84

Trusted Tester Test
[Form not in Sync with Blue Line Representing Completion.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5156631/Form.not.in.Sync.with.Blue.Line.Representing.Completion.mp4.zip)

Brief Description
When completing the Notice of Intention of Marriage, unsure if form actually submitted (even though the website states it has submitted)

Steps to reproduce
1)	00:00, To test the app correctly, tester pre-filled some areas of the app, with video starting on page 2 of 6. Note that the blue line representing partial completion of app is 1/6 filled.
2)	00:08, After scrolling down the page, click the Next button.
3)	00:12, The page successfully advances and the blue line representing partial completion is now 2/6 filled.
4)	00:21, After scrolling down page, select Next button, which advances page, blue line representing partial completion is filled accordingly.
5)	00:24, Note: Confirming an active email (for testing purposes) is input into app so that a confirmation can be sent upon submission.
6)	00:29, Press the Next button, which successfully advances page and blue line gets filled accordingly.
7)	00:41, Press the Submit button. 
8)	00:44, Receive message “Request submitted”. “Your request has been submitted, please look for confirmation email from “boston.gov” in your email at …If more information is need (sic) we will contact at your phone number: 7814895073.”
a)	Bug 1: Grammar. The text should say If more information is needed…
b)	Bug 2: The app does request phone numbers be input without any dashes or spaces. However, the format of the telephone number needs to be consistent with the rest of Boston.gov.
c)	Tester never received confirmation of submission. Unsure if that’s due to the site being in Staging” but will need to be tested again to confirm a successful transmission.
d)  Bug 3:  The status says Step 6 of 6, but the blue line is not showing 100% complete
Desired Result
•	Able to save the Intention to Marry form successfully after filling it out. 

Actual Result
•	Unable to save the Intention to marry form successfully after filling it out.

**Comment by reillyzlab** [comment]
Should not be able to save a copy of the intention after submitting but all the rest of this should be addressed.

For the sake of this ticket, please just address the issue with the blue status bar at the top. The status bar status does not match that of the actual status. 

For other items mentioned in the body of this ticket Reilly will create separate tickets.

**Comment by andrebtlima** [comment]
@david-iterators @jill-iterators this is ready to retest

**Comment by jill-iterators** [comment]
@andrebtlima This bug did not pass and many new bugs are identified in bug report and captured on video plus two screen shots. There is a logic issue causing many of the bugs. I've attached new report and zip video. After you see review the documents, iI can separate into seperate tickets if you want.  I felt it was important for you or Stella to see the issue in its totality first. Let me know if I can do anything to help.


[2020 09 22, Appointment Time and Phone Number on Marriage Application Form.zip](https://github.com/CityOfBoston/Iterators/files/5264524/2020.09.22.Appointment.Time.and.Phone.Number.on.Marriage.Application.Form.zip)
<img width="1517" alt="2020 09 22, Appointment Time and Phone Number on Marriage Application Form 1" src="https://user-images.githubusercontent.com/53226162/93947262-42794c00-fd09-11ea-81ec-917c7c846d5a.png">
<img width="1517" alt="2020 09 22, Appointment Time and Phone Number on Marriage Application Form 2" src="https://user-images.githubusercontent.com/53226162/93947286-4c02b400-fd09-11ea-9b45-d01996d10237.png">

**Comment by andrebtlima** [comment]
@jill-iterators I think this is resolved from our perspective, we just seem to had a different interpretation of what the visual representation of those final stages towards completion should look like (in the form of the status bar). We're going to close for now, but let me know if you think this needs more work.

**Comment by jill-iterators** [comment]
@andrebtlima I agree completely with your decision. The status bar was reported some time ago and I try to be consistent. Thanks for the notice.
