### ISSUE TITLE
The page title does not match the site the page is on and does not differentiate itself between various pages

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#159]
Screengrab/videos (insert file names here)
2020 09 01, Title of page Error.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention?step=partnerFormA

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Chrome 85

Trusted Tester Test
Page Title

Brief Description
The page title does not match the site the page is on and does not differentiate itself between various pages

Steps to reproduce
1)	Go to the Marriage license link
2)	00:03 Page Title shows “Boston.gov – Request a Birth Certificate”

Desired Result
•	The page title adequately describes the content of the page and differentiates it from other pages

Actual Result
•	The title of the page is about getting a birth certificate, not getting a wedding license. It also does not identify which step in the process you are on, which does not allow it to be differentiated from the other pages in the process of getting a marriage license.

**Comment by andrebtlima** [comment]
<img width="1419" alt="Screen Shot 2020-09-08 at 3 26 07 PM" src="https://user-images.githubusercontent.com/57111927/92519313-baaf2000-f1e7-11ea-92c4-7989b79afb09.png">

**Comment by andrebtlima** [comment]
@phillipbentonkelly you can see that the page title in the tab does not match the actual content of the page.

**Comment by phillipbentonkelly** [comment]
I fixed this

**Comment by reillyzlab** [comment]
@andrebtlima to verify

**Comment by reillyzlab** [comment]
This is changed.
