### ISSUE TITLE
Filling in Required form fields does not activate the Next button

### ISSUE THREAD

**Issue by banteneh** [CityOfBoston/Iterators#162]
Screengrab/videos (insert file names here) 
2020 08 31, Filling in Required form fields does not activate the Next button.mp4 

Link 
https://registry-certs.digital-staging.boston.gov/marriageintention 

Node # (if known)

Type of User: Anonymous

Environment
(Device > OS > Browser) 
Computer > Windows 10 > Microsoft Edge 85 

Trusted Tester Test
N/A

Brief Description
Filling in Required form fields does not activate the Next button. 

Steps to reproduce 
1. 00:00 - 00:41, Fill in each required field on the form. 
2. 00:42, Observe, the Next button is not activated. 

Desired Result
Filling in Required form fields activates the Next button.  

Actual Result 
Filling in Required form fields does not activate the Next button. 
[2020 08 31, Filling in Required form fields does not activate the Next button.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5158016/2020.08.31.Filling.in.Required.form.fields.does.not.activate.the.Next.button.mp4.zip)

**Comment by andrebtlima** [comment]
@phillipbentonkelly  this is related to #163. The issue is essentially that the Day/Month/Year fields aren't labelled as required

**Comment by phillipbentonkelly** [comment]
Since we are getting rid of required labels and making all visible fields required before the button is available I think we can close this issue.

**Comment by reillyzlab** [comment]
Agreed, closing
