### ISSUE TITLE
Message indicating date field is required only appears if user clicks or tabs into it

### ISSUE THREAD

**Issue by banteneh** [CityOfBoston/Iterators#163]
Screengrab/videos (insert file names here) 
2020 08 31, Message indicating date field is required only appears if user clicks or tabs into it.mp4 

Link 
https://registry-certs.digital-staging.boston.gov/marriageintention 

Node # (if known) 

Type of User:  Anonymous 

Environment 
(Device > OS > Browser) 
Computer > MacOS > Chrome 85 

Trusted Tester Test 
N/A

Brief Description 
Message indicating date field is required only appears if user clicks or tabs into it. 

Steps to reproduce 
1. 00:00 -13, In the Party A section, enter information into all fields marked ‘Required’.  
2. 00:14, In the next section, Date of Birth, click into the Age field, since it is the only one marked ‘Required’. Skip over the Month, Day, and Year fields. 
3. 00:22, Scroll back up to the beginning of the page and click into the first field. 
4. 00:23, Begin tabbing through each completed field. 
5. 00:30, Observe, after tabbing through Month, Day, and Year fields, 'Please enter a date’ message appears, making the user aware these fields are required.  
This is a bug because the user is only made aware that they must enter information into these fields if they click into it, or tab through it.  

Desired Result 
A form field’s requirement is communicated to the user through multiple modes.  

Actual Result 
Message indicating date field is required only appears if user clicks or tabs into it. 
[2020 08 31, Message indicating date field is required only appears if user clicks or tabs into it.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5158087/2020.08.31.Message.indicating.date.field.is.required.only.appears.if.user.clicks.or.tabs.into.it.mp4.zip)

**Comment by phillipbentonkelly** [comment]
@andrebtlima, Since we are/have removed the required labels from all fields I think we can mark this as done. Let me know if I should be closing these tickets or you; Thanks.

**Comment by andrebtlima** [comment]
@phillipbentonkelly i'll close, thanks
