### ISSUE TITLE
 Phone # field not formatted like other Phone # across boston.gov/web apps

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/Iterators#173]
Link
https://registry-certs.digital-staging.boston.gov/marriageintention?step=reviewRequest

Video

[2020.09.22.Appointment.Time.and.Phone.Number.on.Marriage.Application.Form (1).zip](https://github.com/CityOfBoston/Iterators/files/5268735/2020.09.22.Appointment.Time.and.Phone.Number.on.Marriage.Application.Form.1.zip)

Node # (if known)

Type of User: Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Chrome 85

Brief Description
Checking on some fixes made, per Andre, and find many existing and new issues around dates/times.

Steps to reproduce

Go to the link, https://registry-certs.digitalstaging.boston.gov/marriageintention?step=reviewRequest, also listed above.

- The phone number is required to be entered without any dashes.
   BUG: This should be formatted like all other phone numbers on the City of Boston website, such as 781-489-5083 or 
   other valid phone number formats.
-Directly below the phone number are the words: “numbers only, no spaces, or dashes needed”
  BUG: Note should show the format for the telephone number such as xxx-xxx-xxxx or other valid phone number 
  formats.
  BUG: The phone number is displayed with no formatting.

Desired Result
Phone Number field should accept typical formatted inputs

Actual Result
Phone number field does not accept common formats or valid values.

**Comment by reillyzlab** [comment]
Example can be found at: https://registry.boston.gov/birth/checkout

![Screen Shot 2020-09-24 at 9 21 50 AM](https://user-images.githubusercontent.com/20731897/94150668-0ea04280-fe3f-11ea-94bb-134256ecc038.png)

**Comment by phillipbentonkelly** [comment]
@jimmurphy-boston - This is on Staging for you to checkout.

**Comment by jimmurphy-boston** [comment]
If I tab into the phone number field, I can enter my phone number, if I click into the field (Which is how I would normally expect to fill out the data) I have to highlight the who field before I can enter my phone number. Feels very clumsy

**Comment by phillipbentonkelly** [comment]
I think I fixed the issue.

**Comment by jimmurphy-boston** [comment]
Looks good now

**Comment by phillipbentonkelly** [comment]
Deployed
