### ISSUE TITLE
Issues with "Time" field on Contact form

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/Iterators#174]
Link
https://registry-certs.digital-staging.boston.gov/marriageintention?step=reviewRequest

Video
[2020.09.22.Appointment.Time.and.Phone.Number.on.Marriage.Application.Form (1).zip](https://github.com/CityOfBoston/Iterators/files/5268748/2020.09.22.Appointment.Time.and.Phone.Number.on.Marriage.Application.Form.1.zip)

Type of User: Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.6 > Chrome 85

Brief Description
Checking on some fixes made, per Andre, and find many existing and new issues around dates/times.

Steps to reproduce

- Find the Appointment Time Section and see words saying: “Enter Time in This Format: hh/mm am/pm, example 09:00AM”

-  Enter 09:00
 BUG: Before tester can type “AM” or PM, the Next button is activated, without specifying am/pm.

- Tester went back to the Appointment Time field and input 09:00AM.
BUG: The “Next” button is inactive and will not accept 09:00AM when the “AM” is typed in upper case.

- Tester inputs 09:00PM into Appointment Time Field and “Next” Button is inactive.
 BUG: The time 09:00PM is not accepted in the field. NOTE: Tester did find that the Appointment Time Field does accept lower case am/pm.

- Tester inputs “09:00 A” and note that the field will not allow the “M” to be added to complete “AM”.
 BUG: The space character after 09:00 is not allowed. However, this is the format that is specified above this field.

-Tester inputs “09:00am” and then clicks on the Next button
BUG: the appointment date is listed as 09:00 am A.M. The extra “A.M” is added.
 
Desired Result
Appointment Time field should accept typical formatted inputs

Actual Result
Times field do not accept several formats or valid values. Also the Time is displayed with an extra “A.M.” on the summary

**Comment by reillyzlab** [comment]
Time field was removed altogether so closing this ticket because no longer relevant
