### ISSUE TITLE
Some fields accept negative values 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/Iterators#176]
Two different fields (see screen captures) accept a negative number value . One is on the month of birth and there is no reason for a negative number to be allowed. When you get to the botton of the page you cannot move forward without changing the date. The fix is to remove the negative value and only accept whole numbers from 1-12. The third is on the ZIP code, which have some carrots to move the numbers up and down, to increase or decrease the ZIP code. However, the ZIP code also can't be a negative number so that fix is to remove the ability to place a negative number in the field. 
<img width="1569" alt="2020-09-25_14-59-19" src="https://user-images.githubusercontent.com/53226162/94306471-029ca980-ff41-11ea-973e-3c748d0e9f73.png">
<img width="1569" alt="2020-09-25_14-50-54" src="https://user-images.githubusercontent.com/53226162/94306479-06303080-ff41-11ea-8b53-15908c5d3a02.png">

**Comment by jimmurphy-boston** [comment]
Looks good on staging, I will close this
