### ISSUE TITLE
Party / Person / Partner use is not consistent

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#179]
Screengrab/videos (insert file names here)
Step 1, Party A.png
Step 2, Person A.png
Step 3, Person B.png
Step 5, Partner A and B.png

Link
https://registry-certs.digital-staging.boston.gov/marriageintention?step=partnerFormA

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS 10.15.6 > Safari 14.0

Trusted Tester Test

Brief Description
Party / Person / Partner use is not consistent

Steps to reproduce
1)	Open the link in a private/incognito window.  Fill out the form and note the observations listed below.
2)	Observe “Step 1, Party A.png” and the person is referred to as “Party A”
3)	Observe “Step 2, Person A.png” and the term “Person A” is now used.
4)	Observe “Step 3, Person B.png” and the term “Person B” is used.
5)	Observe “Step 5, Partner A and B.png” and the people are now referred to as “Partner A” and “Partner B”.
6)	BUG:  The people entering into the marriage license are either referred to as Party, Person, or Partner on different screens.
7)  Note:  Accessibility information would need to be updated if any field names are changed

Desired Result
Consistent terms are used across multiple pages

Actual Result
Different terms are used on different pages
<img width="1628" alt="Step 1, Party A" src="https://user-images.githubusercontent.com/33845414/96323859-e0042a80-0fec-11eb-855c-e3f796dcbd96.png">
<img width="1628" alt="Step 2, Person A" src="https://user-images.githubusercontent.com/33845414/96323860-e09cc100-0fec-11eb-8180-fba05ee5ac4c.png">
<img width="1628" alt="Step 3, Person B" src="https://user-images.githubusercontent.com/33845414/96323861-e09cc100-0fec-11eb-8609-c87533eb2a5e.png">
<img width="1628" alt="Step 5, Partner A and B" src="https://user-images.githubusercontent.com/33845414/96323862-e09cc100-0fec-11eb-8dbd-d32c09dc364d.png">

**Comment by banteneh** [comment]
Step 1 still uses terms Party/parties:

![image](https://user-images.githubusercontent.com/64053083/96506570-db768680-1225-11eb-9462-54d135c1d0c3.png)

**Comment by reillyzlab** [comment]
Ensure that all items say person a or person b

**Comment by jimmurphy-boston** [comment]
@phillipbentonkelly Isn't the expected behavior that we use Parties or Person(s) I still se Person for Page  and Partner for final review page?
But I do see Person A for Page 1 So are we only addressing Page 1?

**Comment by phillipbentonkelly** [comment]
@jimmurphy-boston, I missed that one. Check again tomorrow.

**Comment by jimmurphy-boston** [comment]
Looks fine now, thanks
