### ISSUE TITLE
The birth year is updated without notice after changing age

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#180]
Screengrab/videos (insert file names here)
2020 10 16, Birth Year updated without notice.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS 10.5.6 > Chrome 86

Trusted Tester Test

Brief Description
The birth year is updated without notice after changing age

Steps to reproduce
1)	00:00, Go to the link and start filling in the form
2)	00:04, For Person A, enter the year 1990 for the birth year and note that the age is calculated to be 30
3)	00:06, Change the age to 31
a)	Note:  The birth year still remains at 1990
4)	00:14, Go to Person B
5)	00:27, Enter the birth date as 2/2/1990 and the age is calculated as 30
6)	00:32, Change the age to 29
a)	Note:  The birth year still remains at 1990
7)	01:30, Finish entering information for Person B and move to the next string
8)	01:39, Enter an appointment date of 1/1/2021
9)	01:42, Enter the information on the next screen and proceed to the summary screen.
a)	Bug:  The appointment date is listed as Dec 1, 2020, which does not match Jan 1, 2021 that was entered.
b)	Bug:  Partner A birth year was changed to 1989, but that was not shown on the data entry screen at 00:06
10)	01:50:  Bug:  Partner B birth year is shown as 1990, so the age of 29 is inconsistent due to the data entry at 00:32 and is not consistent with the observation for Partner A

Desired Result
Information entered is consistent with the summary

Actual Result
Some items are inconsistent between data entry and the final summary
[2020 10 16, Birth Year updated without notice.zip](https://github.com/CityOfBoston/Iterators/files/5402530/2020.10.16.Birth.Year.updated.without.notice.zip)

**Comment by phillipbentonkelly** [comment]
I'll try to remember to discuss next time we meet. I saw the video and what this is that the age field gets updated when you fill out the `date of birth`  fields but updating the age field does not change the birth fields. I feel like that the age field should not be editable, for several reasons, we should disable editing this field.

**Comment by phillipbentonkelly** [comment]
This is what it looks like. In the second photo it shows you can change the age field and it does not update the date of birth fields.
![COB-Registry-Marriage-Intention-pic1-issue-180](https://user-images.githubusercontent.com/2627273/105532275-9fd1d980-5cb8-11eb-9654-7af89c825798.JPG)
![COB-Registry-Marriage-Intention-pic2-issue-180](https://user-images.githubusercontent.com/2627273/105532276-9fd1d980-5cb8-11eb-98f3-d0fc81c57216.JPG)

**Comment by jimmurphy-boston** [comment]
I agree, it should not be editable, it should be a presentation value.

**Comment by phillipbentonkelly** [comment]
This is on staging

**Comment by phillipbentonkelly** [comment]
deployed
