### ISSUE TITLE
Related by Blood or Marriage for Person A and B can be different

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#181]
Screengrab/videos (insert file names here)
2020 10 16, Related by Marriage Links.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS 10.5.6 > Chrome 86

Trusted Tester Test

Brief Description
Related by Blood or Marriage for Person A and B can be different

Steps to reproduce
1)	00:00, Go to the link and enter the basic information
2)	00:02, Enter that Person B is related by blood or marriage:
a)	Note:  The link was specified as “answer 1”
3)	00:06, Click on Next to go to the Person B screen
4)	00:12, Scroll to the Related to Person A field
a)	Note:  The same information is shown, as consistent with Person A
5)	00:17, Change the relationship to “answer 2”
6)	00:19, Click the Back button to go back to Person A
7)	00:22, Scroll to the Related to Person B field
a)	Bug:  Note that the information still says “answer 1” rather than “answer 2”
8)	00:26, Click on Next to go to the Person B screen
9)	00:30, Scroll to the Related to Person A field
a)	Note:  This field was updated to “answer 1” which is consistent with the previous screen.
10)	00:34, Change the field to “No” and then click on the Back button to go back to Person A
11)	00:40, Scroll to the Related to Person B field
a)	Bug:  the information still says, “answer 1” and was not updated to “No”
12)	00:43, Click on the Next button to go to Person B
13)	00:47, The information was again updated to be consistent with Person A and says “answer 1”

Desired Result
The relationship between Person A and B are kept consistent

Actual Result
The relationship is entered on 2 different screens and the information can be inconsistent.
[2020 10 16, Related by Marriage Links.zip](https://github.com/CityOfBoston/Iterators/files/5402555/2020.10.16.Related.by.Marriage.Links.zip)

**Comment by reillyzlab** [comment]
This is similar to https://github.com/CityOfBoston/Iterators/issues/181 -- the user has not selected 'next' after any of the input, so the answer is not being 'saved' before they go back.

This is acting as expected so closing.
