### ISSUE TITLE
The blood relation is not matching the data entry

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#182]
Screengrab/videos (insert file names here)
2020 10 16, Summary blood information not matching

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > macOS 10.5.6 > Chrome 86

Trusted Tester Test

Brief Description
The blood relation is not matching the data entry

Steps to reproduce
1)	00:00, go to the link and start filling out the form
2)	00:05, Note that the information was entered that there is a relation to Person B and “answer 1” was entered.
3)	00:07, Click on the Next button to move to Person B
4)	00:11, Scroll down to the Related to Person A field
5)	00:14, Change the relationship to “answer 2”
6)	00:15, Click on the Next button
7)	00:18, Click on the Next button to observe the Summary
8)	00:19, Bug:  Note that Partner A states no relation to Partner B, but the blood relation listed as “answer 2”
9)	00:20, Scroll to Partner B
a)	Bug:  The same information is displayed for the blood relation

Desired Result
Information on the summary screen matches the data entry information

Actual Result
The blood relation is not matching the data entry
[2020 10 16, Summary blood information not matching.zip](https://github.com/CityOfBoston/Iterators/files/5402575/2020.10.16.Summary.blood.information.not.matching.zip)

**Comment by andrebtlima** [comment]
@phillipbentonkelly and @reillyzlab this might also be a blocker.

**Comment by andrebtlima** [comment]
@david-iterators we have a fix for this. Would you mind validating?

**Comment by ollie-iterators** [comment]
This issue has been verified as done
