### ISSUE TITLE
Summary page information does not match data entry for several fields

### ISSUE THREAD

**Issue by banteneh** [CityOfBoston/Iterators#183]
Screengrab/videos (insert file names here) 
2020 10 19, Summary page information does not match data entry for several fields.mp4 

Link 
https://registry-certs.digital-staging.boston.gov/marriageintention 

Node # (if known) 

Type of User:  Anonymous 

Environment 
(Device > OS > Browser) 
Computer > macOS 10.14.6 > Chrome 86 

Trusted Tester Test 
n/a 

Brief Description 
Summary page information does not match data entry for several fields.
 
Steps to reproduce

1. 00:04, Start at Parents section for Person A. 
a) Note, Parent 1 is assigned to Mother and Parent 2 is assigned to Father. 
2. 00:11, Scroll down to ‘Were your parents married at the time of your birth?’.  
a) Note, ‘Yes’ is selected.  
3. 00:15, Scroll down to Related by blood or marriage to Person A. 
a) Note, ‘Yes’ is selected. 
4. 00:16, Click Next. 
5. Repeat steps 1-4 for Person B. 
6. 00:39, Click Next on the Step 4 page. 
7. 00:43, on the Summary page look at the Parents section for Person A. 
a) Bug: Parent 1 is designated as Father and Parent 2 is designated as Mother. 
8. 01:02, Look at ‘Were your parents married at the time of your birth?’. 
a) Bug: The answer should say ‘Yes’. 
9. 01:05, Scroll down to ‘Blood Relation to Partner?’. 
a) Bug: The answer should say ‘Yes’. Notice, ‘Describe Blood Relation’ does show up. 
10. Not in video: Repeat steps 7-9 for Person B. 

Desired Result 
Summary page information matches data entered. 

Actual Result 
Summary page information does not match data entry for several fields. 

[2020 10 19, Summary page information does not match data entry for several fields.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5405592/2020.10.19.Summary.page.information.does.not.match.data.entry.for.several.fields.mp4.zip)

**Comment by andrebtlima** [comment]
@phillipbentonkelly and @reillyzlab I think this might be a blocker, unless I'm misunderstanding the ticket.

**Comment by andrebtlima** [comment]
@david-iterators @banteneh we have a fix for this. Would you mind validating?

**Comment by ollie-iterators** [comment]
This has been verified as completed
