### ISSUE TITLE
Clicking Back button erases edits made on the page

### ISSUE THREAD

**Issue by banteneh** [CityOfBoston/Iterators#184]
Screengrab/videos (insert file names here) 
2020 10 19, Click Back button erases edits made on the page.mp4 
Link 
https://registry-certs.digital-staging.boston.gov/marriageintention 

Node # (if known) 

Type of User:  Anonymous 

Environment 
(Device > OS > Browser) 
Computer > macOS 10.14.6 > Chrome 86 

Trusted Tester Test 
n/a 

Brief Description 
Clicking Back button erases edits made on the page. 

Steps to reproduce 
1. 00:01, Starting at Step 3 (Person B), scroll down to the Parents section. 
2. 00:08, Change ‘Mother first name’ to MotherFirst. 
3. 00:12, Change ‘Mother last name’ to MotherLast. 
4. 00:16, Change Father first name’ to FatherFirst. 
5. 00:22, Change Father last name’ to FatherLast. 
6. 00:25, Scroll to the bottom of the page, then click Back to view the previous page. 
7. 00:29, Scroll to the bottom of the page, then click Next to return to Step 3. 
8. 00:34, Scroll down to the Parents section, where the changes were made. 
a) **Bug**: Updates weren’t saved.
10. 00:42, Repeat Steps 2-5.
11. 01:11, Scroll to the bottom of the page, then click Next to advance to Step 4. 
12. 01:13, Scroll to the bottom of the page, then click Back to return to Step 3. 
13. 01:16, Scroll down to the Parents section, where the changes were made. 
a) Observe, changes were saved.  
15. Not in video: These changes were reflected on the Summary page (Step 5).  

Desired Result 
Clicking Back button does not erase edits made on the page. 

Actual Result 
Clicking Back button erases edits made on the page. 

[2020 10 19, Clicking Back button erases edits made on the page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5405843/2020.10.19.Clicking.Back.button.erases.edits.made.on.the.page.mp4.zip)

**Comment by reillyzlab** [comment]
This is acting as expected. There is so no autosave for the application. The information is 'saved' (and in this case updated) when someone clicks next.

Going to close.
