### ISSUE TITLE
Parent 1 and parent 2 are swapped on the confirmation page

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#185]
Environment
(Device > OS > Browser)
Computer > Windows 10 > Chrome 85.0.4183

Brief Description
Parent 1 and parent 2 are swapped on the confirmation page

Steps to reproduce
1)	Fill out form as usual
Make sure information is all recognizable, as seen in “2020 10 22 Parent 1 and 2 are swapped 1.png” and “2020 10 22 Parent 1 and 2 are swapped 2.png”
BUG: when you finish the form and it shows the information, notice that the info of “Parent 1/Mother” information from the form is applied to “Parent 1/Father” on the review page, as is “Parent 2/Father” is applied to “Parent 2/Mother” on the review page, as seen in “2020 10 22 Parent 1 and 2 are swapped 3.png”
a)	NOTE: it’s not depicted for person B, but this applies to the parents of both Person A and Person B

Desired Result
•	Form elements remain constant

Actual Result
•	Form elements are mis-labeled on the review page

<img width="876" alt="2020 10 22 parent 1 and 2 are swapped 1" src="https://user-images.githubusercontent.com/53226162/97212140-5c89cc80-1796-11eb-9114-4f19e36fd50a.png">
<img width="871" alt="2020 10 22 parent 1 and 2 are swapped 2" src="https://user-images.githubusercontent.com/53226162/97212162-60b5ea00-1796-11eb-8efd-221222096e03.png">
<img width="842" alt="2020 10 22 parent 1 and 2 are swapped 3" src="https://user-images.githubusercontent.com/53226162/97212170-64497100-1796-11eb-8276-095604aea5a2.png">

There is no video, three screen shots attached.

**Comment by andrebtlima** [comment]
@reillyzlab this ticket was duplicative of #186 so not sure if that's been fixed.

**Comment by reillyzlab** [comment]
Closing -- resolved via: https://github.com/CityOfBoston/digital/issues/693
