### ISSUE TITLE
Parent 1 and parent 2 are swapped on the confirmation page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#186]
Screengrab/videos (insert file names here)
2020 10 22 Parent 1 and 2 are swapped 1.png
2020 10 22 Parent 1 and 2 are swapped 2.png
2020 10 22 Parent 1 and 2 are swapped 3.png

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 > Chrome 85.0.4183

Brief Description
Parent 1 and parent 2 are swapped on the confirmation page

Steps to reproduce
1)	Fill out form as usual.  Make sure information is all recognizable.  The parent information is shown in the following screen captures:   “2020 10 22 Parent 1 and 2 are swapped 1.png” and “2020 10 22 Parent 1 and 2 are swapped 2.png”
2)	Proceed to the summary page.  BUG: Notice that the info of “Parent 1/Mother” information from the form is applied to “Parent 1/Father” on the review page, as is “Parent 2/Father” is applied to “Parent 2/Mother” on the review page, as seen in “2020 10 22 Parent 1 and 2 are swapped 3.png”
a)	NOTE: it’s not depicted for person B, but the parent names are swapped for person B as well.

Desired Result
•	Form elements remain constant

Actual Result
•	Form elements are mis-labeled on the summary page
<img width="876" alt="2020 10 22 parent 1 and 2 are swapped 1" src="https://user-images.githubusercontent.com/33845414/97245555-b360c780-17d1-11eb-8b31-4016b4e2ac1c.png">
<img width="871" alt="2020 10 22 parent 1 and 2 are swapped 2" src="https://user-images.githubusercontent.com/33845414/97245557-b3f95e00-17d1-11eb-922d-c20be199934d.png">
<img width="842" alt="2020 10 22 parent 1 and 2 are swapped 3" src="https://user-images.githubusercontent.com/33845414/97245558-b3f95e00-17d1-11eb-8d09-0f282dd3c34a.png">

**Comment by andrebtlima** [comment]
@david-iterators is this a different issue than #185? I'm seeing some duplication but maybe I'm missing something

**Comment by david-iterators** [comment]
Sorry, this is the same as #185 , so I will go ahead and close this issue.
