### ISSUE TITLE
Upon submitting marriage intention, you cannot get back to marriage intention form page directly

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#187]
Screengrab/videos (insert file names here)
2020 10 19 error getting back to start page.mp4

Link
https://registry-certs.digital-staging.boston.gov/marriageintention

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 > Chrome 85.0.4183

Brief Description
Upon submitting marriage intention, you cannot get back to marriage intention form page directly

Steps to reproduce
1)	00:00 Launch website in a private browser
2)	00:01 fill out forms as normal
3)	03:01 submit form
4)	03:08, When request is submitted, click “Marriage Intention” on the top
5)	03:08 BUG: “something went wrong! We had a technical issue that we don’t know how to handle, but our staff is working to fix it.”

Desired Result
Clicking the link to redirect back to the marriage intention form takes you back to the form

Actual Result
“Something went wrong” message
[2020 10 19 error getting back to start page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5442375/2020.10.19.error.getting.back.to.start.page.mp4.zip)

**Comment by reillyzlab** [comment]
When a user clicks on the breadcrumb they should be taken to the introduction page for the application.

**Comment by phillipbentonkelly** [comment]
Based on the last comment it seems the breadcrumbs covers this issue, moving it to DONE. Can be closed later
