### ISSUE TITLE
VPAT 3.2.2, Changing Fields

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#19]
Link
https://permit-finder.digital-staging.boston.gov

Environment
(Device > OS > Browser)
Computer > macOS 10.14.6 > Safari 12.1.2

Brief Description
Search results are not identified in the form.

Steps to reproduce
1. See “1 Search Results.png”.  Only the phone number is highlighted with a field in the search results.
2. See “5, Invalid Permit.png”.  The invalid permit ID message is not highlighted with a field.

Desired Result
Search results are identified.

Actual Result
Search results not identified.
![5, Invalid Permit](https://user-images.githubusercontent.com/33845414/62466980-aedd6880-b760-11e9-89df-59311d552d52.png)
![4  Search Results](https://user-images.githubusercontent.com/33845414/62466981-af75ff00-b760-11e9-8b1f-4cf75e4b7c11.png)

**Comment by phillipbentonkelly** [comment]
@paylakatel this is now on Staging

**Comment by paylakatel** [comment]
Looks great on staging - thank you! We can move it into production

**Comment by phillipbentonkelly** [comment]
Deployed, Live; Leaving the ticket un-closed until Monday
