### ISSUE TITLE
2020 11 04 Error message when using 50 Milk Street.mp4

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#190]
Screengrab/videos (insert file names here)
2020 11 04 Error message when using 50 Milk Street.mp4

Link
https://www.boston.gov/my-neighborhood

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser
Computer > MacOs 10.15.7 > Chrome 86.0

Trusted Tester Test
[2020 11 04 Error message when using 50 Milk Street.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5489598/2020.11.04.Error.message.when.using.50.Milk.Street.mp4.zip)

Brief Description
When adding address to the address field, receive message the address cannot be found by that name.

Steps to reproduce
1)	00.00, Paste the link noted above into a private browser window, press Return.
2)	00:16, In the Enter Your Address field, type 50 Milk St, Boston and note the message “no address was found by that name”
3)	00:29, Edit the information in the Enter Your Address by changing “ST” to Street. Note message stating “no address was found by that name”
4)	00:36, Edit the information entered in the Enter Your Address by adding MA to the address so the field reads, 50 Milk Street, Boston, MA 02109. Note a message stating “no address was found by that name.”
5)	This is a bug because the address is a correct address in the City of Boston, and when added to the search field provides the error.
a)	Note: The actual ZIP code of 50 Milk Street, Boston, MA is 02109 based on Google Search. However, the video shows, as an example (at 10 seconds) addresses such as 50 Milk Street, #20, Boston, MA 02108. Unsure if this is why the address is not found or what criteria is used to determine if address is correct.

Desired Result
•	Able to find 50 Milk Street, Boston, MA 02109 successfully in the My Neighborhood Search field.

Actual Result
•	Unable to receive results for a correct address, 50 Milk Street, Boston, MA 02109 successfully. Unsure what criteria is being used to determine why address is not accepted.

**Comment by jill-iterators** [comment]
[Uploading 2020 11 04 Error message when using 50 Milk Street.mp4.zip…]()

**Comment by jill-iterators** [comment]
Both links under Historic district have the same issue and need to be opened in a new window.

**Comment by jill-iterators** [comment]
most of the links on this link, https://www.boston.gov/my-neighborhood?p3 need to be fixed to open a new window

**Comment by reillyzlab** [comment]
Closing because this is behaving as expected. Can't do anything to resolve; working with the data we have available.
