### ISSUE TITLE
2020 11 04 Text Overlaps Search Icon When Making the Screen Smaller.mp4

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#191]
Screengrab/videos (insert file names here)
2020 11 04 Text Overlaps Search Icon When Making the Screen Smaller.mp4

Link
https://www.boston.gov/my-neighborhood?p2

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Chrome 86.0

Trusted Tester Test

Brief Description
Text and Search Overlap When Making the Screen Smaller.mp4
[2020 11 04 Text and Search Overlap When Making the Screen Smaller.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5490139/2020.11.04.Text.and.Search.Overlap.When.Making.the.Screen.Smaller.mp4.zip)

Steps to reproduce
1)	00:00, Open the link in a private browser window and then return.
2)	00:06, Go to the right side of the computer screen and with cursor start making screen narrower. 
3)	00:16, Note the Search field and that the icon is overlapping the ZIP Code and that the ZIP Code is truncated. 

This is a Functional bug.

Desired Result
•	Albe to see text and icons without any overlap

Actual Result
•	Unalbe to see text and icons without any overlap

**Comment by jill-iterators** [comment]
[2020 11 04 Text and Search Overlap When Making the Screen Smaller.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5490146/2020.11.04.Text.and.Search.Overlap.When.Making.the.Screen.Smaller.mp4.zip)

**Comment by jill-iterators** [comment]
I tested this issue on an iPad 12.9 and did not find the issue, but also used iPhone 10 and the issue was present. 
[text and icon collide.pdf](https://github.com/CityOfBoston/Iterators/files/5490389/text.and.icon.collide.pdf)

**Comment by reillyzlab** [comment]
Tested on iPhone X and the text does resize and is fine/operating as it should.

However, when accessing on desktop/laptop browsers at smaller breakpoints this is an issue.

![Screen Shot 2020-11-17 at 5 58 29 PM](https://user-images.githubusercontent.com/20731897/99460802-256e8d00-28f6-11eb-8cc8-263152a270ac.png)

**Comment by subaha-cob** [comment]
@jill-iterators  UAT is now up with MNL tickets. 
https://d8-uat.boston.gov/

Try testing with this addresses only:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
![IMG_6032](https://user-images.githubusercontent.com/20731897/102637386-88348d80-411b-11eb-8845-eba2caf72757.PNG)

@subaha-cob this is how it is appearing on iPhone X which seems too small, can we find a happy medium between this too small and overlapping?

**Comment by subaha-cob** [comment]
@reillyzlab I just updated UAT with a fix. Please retest on UAT. Thanks!

**Comment by ollie-iterators** [comment]
This bug has been fixed
