### ISSUE TITLE
The Alt-Text for some images on the main page contain redundant text

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#194]
Screengrab/videos (insert file names here)
2020 11 09, Redundant Text on Alt-Text for Images.mp4
[2020 11 09, Redundant Text on Alt-Text for Images.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5511975/2020.11.09.Redundant.Text.on.Alt-Text.for.Images.mp4.zip)

Link
https://d8-stg.boston.gov/

Node # (if known)
21

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Chrome 68

Trusted Tester Test
Images

Brief Description
The Alt-Text for some images on the main page contain redundant text

Steps to reproduce
1)	00:00, Load the URL
2)	00:02, First image with redundant text for the alt-text. It says the image is an “Image for …”
a)	Note: The name in the sentence also needs to be capitalized properly like the other images
3)	00:03, Second Image with redundant text for the alt-text. The alt-text says that it is a “Ricardo Arroyo photo”, which is unnecessary
4)	00:07, Third Image with redundant text for the alt-text. It says the image is an “Image for …”
a)	Note: The name in the sentence also needs to be capitalized properly like the other images
5)	00:14, Fourth Image with redundant text for the alt-text. It says the image is an “Image for …”
a)	Note: It also appears the alt-text contains text that may be part of an email address for the person “flaherty360” instead of the person’s name. Also, when the name is added it needs to be properly capitalized
6)	00:29, Fifth Image with redundant text for the alt-text. It says the image is an “Image for …”
a)	Note: The name in the sentence also needs to be capitalized properly like the other images

Desired Result
•	The images all have correct alt-text with no redundant text in them

Actual Result
•	The images for these people contain redundant alt-text:
o	Andrea Campbell
o	Ricardo Arroyo
o	Ed Flynn
o	Michael Flaherty
o	Mayor Martin J Walsh

**Comment by subaha-cob** [comment]
All set on https://www.boston.gov/

**Comment by ollie-iterators** [comment]
This appears to have been fixed
