### ISSUE TITLE
There is an image on the News page that has redundant text on the page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#196]
Screengrab/videos (insert file names here)
2020 11 09, Redundant phrase in image.png
![2020 11 09, Redundant phrase in image](https://user-images.githubusercontent.com/46904826/98587036-9d560b00-2297-11eb-8f23-35b5c3d68c20.png)

Link
https://d8-stg.boston.gov/news

Node # (if known)
1401-latest

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Chrome 68

Trusted Tester Test
Images

Brief Description
There is an image on the News page that has redundant text on the page

Steps to reproduce
1)	Load the URL
2)	Go down the page until you get to the story with the title “$17.2 million renovation of the Roxbury library branch completed”
3)	Right click on the image for the article and inspect it

Desired Result
•	The alt-text for the image contains no redundant phrases

Actual Result
•	The alt-text for the image says, “Photo of interior of Roxbury Branch with public artwork”. This is a redundant phrase.

**Comment by subaha-cob** [comment]
@jill-iterators content is gone.

**Comment by ollie-iterators** [comment]
![2021 03 30, Redundant phrase in alt text for Image](https://user-images.githubusercontent.com/46904826/113045577-04a02900-916d-11eb-8b29-e0f6fd70f413.png)

There is now another image that has redundant text on the Boston.gov/news site. The alt-text for the image says "Photo of youth in BPHC VIP initiative"

**Comment by subaha-cob** [comment]
This is one of those things that is out of our control unless the content editors start taking notes and making sure they are complying to all the accessibility rules as well.

**Comment by subaha-cob** [comment]
Nothing more we can do here.
