### ISSUE TITLE
Search results do not match entry

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#201]
Screengrab/videos (insert file names here)
2020 11 07, Search results do not match entry.mp4

Link
https://www.boston.gov/my-neighborhood

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Safari

Trusted Tester Test
Functional

Brief Description
Search results do not match entry

Steps to reproduce
1)	00:00, Open the link in a private browser window
2)	00:05, Enter a search “50 milk st” and results are visible.  Notice that one of the results is “50 Milk St #20 Boston, 02108”
3)	00:10, Enter a search of “50 milk st 20” and no results are shown
4)	00:13, Enter a search of “50 milk st #20” in order to match one of the search results shown previously.
a)	BUG:  a number of results are shown and many do not contain the #20 in result.
5)	00:21, Enter a search of “50 milk st #20 02109” and the same results are shown.
a)	BUG:  the displayed zip codes in the list are 02108 which does not match the search term of 02109

Desired Result
•	Search results match the criteria provided in the search field

Actual Result
•	Search results do not always match the search criteria
[2020 11 07, Search results do not match entry.zip](https://github.com/CityOfBoston/Iterators/files/5514496/2020.11.07.Search.results.do.not.match.entry.zip)
Andre

**Comment by reillyzlab** [comment]
Closing because this is behaving as expected. Can't do anything to resolve; working with the data we have available.
