### ISSUE TITLE
Alt Text for "Back to Top" Graphic has a typo

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#211]
Link
https://www.boston.gov/public-notices/64966

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 11.4 > Chrome 91

Trusted Tester Test
Alt Text

Brief Description
There is an image on the link that has a typo in the alt text
 Steps to reproduce
1)	Go to the URL
2)	Scroll down to the bottom of the page
3)	Right click on the image “Back To Top” and click “Inspect”
a)	Bug: The alt-text for the image says “Back Top Top” instead of “Back To Top”

Desired Result
•	The alt text for images are spelled correctly

Actual Result
•	The alt-text for the “Back To Top” image says “Back Top Top” instead of Back To Top
•	

<img width="780" alt="2021-06-06_15-44-02" src="https://user-images.githubusercontent.com/33845414/120937880-0abb0480-c6de-11eb-96bc-3b8146ba97c2.png">

**Comment by subaha-cob** [comment]
@david-iterators this is all set on UAT https://d8-uat.boston.gov/

**Comment by ollie-iterators** [comment]
This has been fixed
