### ISSUE TITLE
Extra empty level 1 Header on Page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#214]
Screengrab/videos (insert file names here)
2021 06 03, Extra empty level 1 Header on Page.png

Link
https://www.boston.gov/public-notices/64966 

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 11.4 > Chrome 91

Trusted Tester Test
Headers

Brief Description
Extra empty level 1 Header on Page

Steps to reproduce
1)	Go to the URL
2)	Inspect the page in the area above the header “PUBLIC FACILITIES COMMISSION MEETING (DND)”
a)	Bug: There is an extra level 1 header with no text in it.

Desired Result
•	All the headers on the page have text and there is only one level 1 header.

Actual Result
•	There is a level 1 header on the page that has no text in it

**Comment by david-iterators** [comment]
![2021 06 03, Extra empty level 1 Header on Page](https://user-images.githubusercontent.com/33845414/121022701-941b1700-c770-11eb-81cf-2868ec2e55a2.png)

**Comment by subaha-cob** [comment]
@david-iterators this is all set on UAT https://d8-uat.boston.gov/

**Comment by ollie-iterators** [comment]
This has been fixed
