### ISSUE TITLE
2021 12 05, QA, Link to Main Page UAT goes to 404 page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#219]
Screengrab/videos (insert file names here)

Tester (first name)
Oliver

Link
https://www.loom.com/share/ecdead9c933942cd954990f0a6f2bc42 
Production URL: https://www.boston.gov/
UAT URL: https://d8-uat.boston.gov/

Environment
(Device > OS > Browser)
Computer > MacOS 12.0.1 > Chrome 96

Brief Description
Link on Main Page/UAT goes to 404 page

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Load the URL for UAT
2)	00:08, Right click on the link “Reopening in Boston”
a)	BUG: The link that shows up in the next tab says “404 Not Found”

Desired Result
•	The link goes to a valid page

Actual Result
•	The link goes to a 404 page

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob closing this one out as its no longer an active link on the homepage.
