### ISSUE TITLE
2021 12 05, QA, Common Resources has different options and different spacing underneath

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#220]
Screengrab/videos (insert file names here)
2021 12 02, Common Resources has different spacing underneath – Production.jpg
2021 12 02, Common Resources has different spacing underneath – UAT.jpg

Tester (first name)
Andrew

Link
Production URL: https://boston.gov/
UAT URL: https://d8-uat.boston.gov/

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Brief Description
Common Resources has different options and different spacing underneath

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	Launch the Production page and the UAT page in private browsers
2)	Scroll down to “common resources”
3)	INCONSISTANCY: at the bottom of the page, there is extra space between the grid of resources on the production page compared to the UAT page (highlighted with the green circle)

Desired Result
•	Format matches between documents

Actual Result
•	Common Resources has different spacing underneath

**Comment by subaha-cob** [comment]
@david-iterators This is fine for now. Moving forward you will notice I also fix spacing issues or made than better. I will leave the decision of when to log in a bug to you. But this is not a bug. This was intentional.

**Comment by david-iterators** [comment]
Closed based on the above comment
