### ISSUE TITLE
Human Resources, 2 columns

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#225]
Brief Description
Human Resources, 2 columns

Screengrab/videos (insert file names here)
https://www.loom.com/share/9424897677574390a8178e6c195f7506

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/career-center
UAT URL: https://d8-uat.boston.gov/career-center

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch UAT page in Private browser
2)	00:11, scroll down to “Contact Human Resources”
3)	00:24, reduce screen width
a)	00:34, BUG: the contact information column is not vertically aligned with the body text column
4)	00:44, repeat steps 1-3 with the Production page in private browser
a)	01:14, the contact information column and body text column are vertically aligned

Desired Result
•	UAT and Production formatted the same

Actual Result
•	UAT 2 column display is out of sync at some window widths.

**Comment by Andrew-Iterators** [comment]
This bug has been resolved
