### ISSUE TITLE
My Brothers Keeper, 2 columns

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#226]
Brief Description
My Brothers Keeper, 2 columns

Screengrab/videos (insert file names here)
https://www.loom.com/share/2087fc44ca4b4b918a594200626fe76b

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/civic-engagement/my-brothers-keeper-boston
UAT URL: https://d8-uat.boston.gov/civic-engagement/my-brothers-keeper-boston

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch both pages in Private browser
a.	00:05, The UAT page is displayed on the left and the Production page is displayed on the right
2)	00:11, BUG: the right column is farther to the right on the UAT page
3)	00:18, scroll down to fully view the “About the Program” content
4)	00:22, BUG: the right column is also farther to the right on the UAT page
a.	00:30, Possible Bug: the Production Page’s right column has more information and uses a different format to display it than on the UAT page

Desired Result
•	UAT and Production formatted the same

Actual Result
•	Both UAT 2 column display is at a different width and has some different format of content display than the Production Page.

**Comment by Andrew-Iterators** [comment]
The "right column is also farther to the right on the UAT page" bug is resolved.

the difference in content is still present, but if that is intended, then this report is completely resolved
