### ISSUE TITLE
My Brother’s Keeper, Numbered Bullet Points

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#227]
Brief Description
My Brother’s Keeper, Numbered Bullet Points

Screengrab/videos (insert file names here)
https://www.loom.com/share/ef18c5bc77e447cd86c1615a0befe851

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/civic-engagement/my-brothers-keeper-boston
UAT URL: https://d8-uat.boston.gov/civic-engagement/my-brothers-keeper-boston

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browsers
a.	00:05: In the video the UAT page is on the left, and the Production Page is on the right
2)	00:10, scroll down to fully view “About the Program” on both pages
3)	00:14, BUG: on the UAT page, the Ordered bullet points are all listed as “1”, where as on the Production page they are listed as “1” to “4”

Desired Result
•	Ordered Bullet Points are correctly ordered

Actual Result
•	Bullet points are incorrectly numbered

**Comment by Andrew-Iterators** [comment]
his bug report is resolved
