### ISSUE TITLE
Events, Bullet points are incorrectly numbered

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#228]
Brief Description
Events, Bullet points are incorrectly numbered

Screengrab/videos (insert file names here)
https://www.loom.com/share/1bd20d1627994d74a43b5da114400ac7

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/calendar/west-end-community-preservation-neighborhood-meet-and-greet
UAT URL: https://d8-uat.boston.gov/calendar/west-end-community-preservation-neighborhood-meet-and-greet

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browsers
a)	00:03: In the video the UAT page is on the left, and the Production Page is on the right
2)	00:10, BUG: on the UAT page, the Ordered bullet points are all listed as “1”, where as on the Production page they are listed as “1” to “4”

Desired Result
•	Ordered Bullet Points are correctly ordered

Actual Result
•	Bullet points are incorrectly numbered

**Comment by Andrew-Iterators** [comment]
this bug has been resolved
