### ISSUE TITLE
Career Center, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#229]
Brief Description
Career Center, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/93769fc7fa8c44609f0873a1cafe4c4f

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/career-center
UAT URL: https://d8-uat.boston.gov/career-center

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a)	00:03, The UAT page is on the left, and the Production Page is on the right
2)	00:13, BUG: the spacing between the “Public health commission” header and the body text is much greater on the production page
3)	00:40, BUG: spacing between the “Career center help” header and body text is slightly greater on the UAT page.
a)	00:51, BUG: the space between the body text and the below image is significantly greater on the Production page.
4)	01:12, BUG: the spacing between the image and “Hear more stories” header is greater on the Production page.
5)	01:38, BUG: the spacing between the “Hear mor Stories” examples and the map is greater on the production page.
6)	02:21, BUG: the spacing between Benefits and “Help with Multi-Step Applications” is greater on the production page
a)	NOTE: The spacing is evenly distributed between the standard grey background and the Darker background.
7)	02:38, BUG: the spacing between “Help with Multi-Step Applications” and “Additional Ways to search jobs” is greater on the production page
a)	NOTE: The spacing is evenly distributed between the standard grey background and the Darker background.
8)	03:01, BUG: the spacing of the gray area under “Additional Ways to search jobs” is greater on the production page
9)	03:13, the font size of the “Contact Human Resources” is smaller on the Production page
10)	03:22, BUG: the spacing between “Download Brochures” and “Hear from Employees” is greater on the production page
a)	NOTE: The spacing is evenly distributed between the standard grey background and the Darker background.
11)	03:23, BUG: the spacing of the gray area after “Hear from Employees” is greater on the production page

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	Page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators Won't fix. This content is coming directly from the database. I can't really do much until we move to Production unfortunately. Content changes can be retested on Production when we get there.

RETEST ON Production!!!! Pending Production Deploy.
https://www.boston.gov/career-center

**Comment by david-iterators** [comment]
Will retest on production

**Comment by subaha-cob** [comment]
@david-iterators the content should be the same now. Retest content changes on staging and close ticket if the content are now the same.

**Comment by david-iterators** [comment]
Verified on Staging
