### ISSUE TITLE
City of Boston Government, page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#230]
Brief Description
City of Boston Government, page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/48c6274e523d428d86c2a6faf7910375

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/departments/311/city-boston-government
UAT URL: https://d8-uat.boston.gov/departments/311/city-boston-government

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
1)	00:01, The Production page is on the left, and the UAT Page is on the right
2)	00:10, BUG: the font size of “Learn about our elected officials, as well as the leaders of our cabinets and departments” is slightly larger on the Production Page
3)	00:20, BUG: the space above and below the Mayor on the Production page is greater than that of the UAT page
4)	00:45, BUG: the spacing between each of the Cabinets on the Production Page is greater than that of the UAT page 
5)	02:20, BUG: the font size for “Boards of Commissions” is slightly larger on the Production Page

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators Won't fix. Spacing was fixed on UAT because it looked squash/or too large on production. Content changes can be retested on Staging when we get there.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by david-iterators** [comment]
Verified on staging
