### ISSUE TITLE
Departments, page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#231]
Brief Description
Departments, page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/ea08dec21cc3404d882fe13fe478c492

Tester (first name)
Andrew

Link
Production URL: https://d8-uat.boston.gov/departments UAT URL: https://d8-uat.boston.gov/departments

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a.	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:12, BUG: the spacing under the “Frequently Used Departments” is greater on the UAT page
a.	Not highlighted in video, the vertical space between the different rectangles is a little bigger in the on the UAT page
3)	00:25, BUG: the space below “Frequently Used Departments” and above “All Departments” is greater on the Production page.

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators Won't fix. Spacing was fixed on UAT because it looked squash/or too large on production. Content changes can be retested on Staging when we get there.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by david-iterators** [comment]
Verified on Staging
