### ISSUE TITLE
Events, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#232]
Brief Description
Events, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/2a5daee7dc8a423785b9cd816c644686

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/events
UAT URL: https://d8-uat.boston.gov/events

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a)	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:11, BUG: space above “EVENTS” is greater in the UAT page
3)	00:22, BUG: space above the dates is greater on the UAT page
4)	00:30, Scroll down to the bottom of the page,
a)	UAT page does not have enough events over enough months to compare the spacing
5)	00:39, BUG: the grey space above “other calendars is greater on the Production page

Desired Result
•	Ordered Bullet Points are correctly ordered

Actual Result
•	Bullet points are incorrectly numbered

**Comment by subaha-cob** [comment]
@david-iterators Won't fix. Spacing was fixed on UAT because it looked squash/or too large on production. Content changes can be retested on Staging when we get there.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
This bug report has been resolved.

there is definitely a difference in databases for the upcoming events, so that should be taken note of and resolved if nessessary
