### ISSUE TITLE
Parks and Playgrounds, page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#233]
Brief Description
Parks and Playgrounds, page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/ea08dec21cc3404d882fe13fe478c492

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/parks-and-playgrounds UAT URL: https://d8-uat.boston.gov/parks-and-playgrounds

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a)	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:12, BUG: the spacing above the page header is greater on the UAT page
3)	00:23, BUG: the spacing above the search bar is greater on the UAT page
4)	00:33, BUG: the spacing below the specific parks is greater on the UAT page

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by Andrew-Iterators** [comment]
Spacing differences have been resolved.

The font for the different Park names are different between the two site versions (Bold and all capitals on the UAT page.) if this is intentional, than this bug report is resolved

**Comment by david-iterators** [comment]
Verified on Staging
