### ISSUE TITLE
Pay and Apply, page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#234]
Brief Description
Pay and Apply, page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/abf9e41fb9924953a322434e18239e51

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/pay-and-apply
UAT URL: https://d8-uat.boston.gov/pay-and-apply

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a.	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:12, BUG: the spacing above the title is greater in UAT page
3)	00:24, BUG: the lighter spacing below the title and body text is greater on the UAT page
4)	00:31, BUG: the gray spacing above “Common payments and forms” is greater on the Production page.
a.	NOTE: this gray spacing on the Production page is greater than the gray spacing and the increased light spacing combined.
5)	00:42, BUG: “What do you need help with?” section is not present on the UAT page, with the Gray area ending after “Common Payments and forms”
6)	00:42, BUG: the search bar and “Main Transactions” section is not present in the Production page
7)	00:50, BUG: the spacing below “Common Payments and Forms” and above “What do you need help with” is greater on the Production page than the one below “Common Payments and Forms” and above the Search bar and “MainStransactions” on the UAT page

Desired Result
•	Spacing and Font Size are the same

Actual Result
page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators Won't fix. Spacing was fixed on UAT because it looked squash/or too large on production. Content changes can be retested on Staging when we get there.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
this bug report is resolved

**Comment by david-iterators** [comment]
Verified on staging
