### ISSUE TITLE
West End Community Meet n Greet, page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#235]
Brief Description
West End Community Meet n Greet, page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/7dec6f35e9544facb992d2381da95365

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/calendar/west-end-community-preservation-neighborhood-meet-and-greet
UAT URL: https://d8-uat.boston.gov/calendar/west-end-community-preservation-neighborhood-meet-and-greet

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a)	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:10, BUG: spacing above header is greater on the UAT page
3)	00:20, BUG: spacing below header is slightly greater in the Production URL
4)	00:28, BUG: Space below “IN CASE YOU MISSED IT” is greater on the UAT page.
5)	00:39, BUG: the space between “Discussion Topics” and the bullet points is greater on the UAT page.
6)	Not Portrayed in Video: BUG: the spacing below the bullet points is greater on the UAT page.

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators. Spacing/padding issue will not be fixed because it was "Fixed" for UAT. Other issues should be tested.

**Comment by Andrew-Iterators** [comment]
This bug report has been resolved
