### ISSUE TITLE
Food Truck Schedule, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#236]
Brief Description
Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/5911ee726bc5437a91b266cec05bf666

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule
UAT URL: https://d8-uat.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browsers
a)	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:10, BUG: the spacing above the title heading is greater in the UAT page than the Production page
3)	00:21, BUG: the spacing below the title heading and the sub-heading is wider on the Production page than the UAT page.
4)	00:27, BUG: the space below the sub-heading on the UAT page is slightly narrower than the one on the Production page
5)	00:35, BUG: the space between the heading and the contact information collumn is significantly wider on the Production page than the UAT page.
6)	00:47, BUG: the squiggly line divider is longer on the UAT page than the Production page, bleeding into the space between the heading and the contact information
7)	01:14, BUG: the space above the map is significantly wider on the production page than the UAT page.
8)	01:21, BUG: the spacing between the map and “Locations by Neighborhood” is wider on the Production page than the UAT page.
a)	The space on the Production page has a horizontal line in the middle of it where the background turns from white to gray which is not present in the UAT page.
9)	01:36, BUG: the “Locations by Neighborhood” section has 8 entries while the Production page has only 7, making the UAT page’s section longer than the UAT section

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators spacing was redone for the most part. Unless the designers complain, I will it is fine on this page.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
this bug report has been resolved

**Comment by Andrew-Iterators** [comment]
the spacing is not resolved.

the difference in number of stops is resolved.

**Comment by david-iterators** [comment]
Verified on Staging
