### ISSUE TITLE
How To CPR Training, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#237]
Brief Description
How To CPR Training, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/08dbe5a9fb4543c4837d399b9af2692d

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/departments/emergency-medical-services/cpr-training
UAT URL: https://d8-uat.boston.gov/departments/emergency-medical-services/cpr-training

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browsers
a)	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:13, BUG: the space between the Directory and the Sub-Header (“Cardiopulmonary Resuscitation (CPR) is a lifesaving technique. Boston EMS offers...”) is wider on the UAT page than the Production page
3)	00:25, BUG: the space between the body content on the left and the content on the right is much wider on the Production page than the UAT page.
4)	00:44, BUG: the formating of certain body text (starting with“We encourage everyone to learn...”) is formatted completely differently 
a)	The font is italicized and much larger on the UAT page than the production page
5)	00:53, BUG:  the “Individual CPR Certificate” is located below “Why is CPR important” section, but is in the right margin with the page information on the UAT page

Desired Result
•	Spacing and Font Size are the same

Actual Result
page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
@david-iterators spacing was redone on this page deliberately. Unless otherwise mentioned, we are good.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
spacing was resolved,
formatting is partially resolved. the "We encourage..." through "CPR and Heart-Health" sections of "WHY IS CPR IMPORTANT" is now in a seperate column on the right, but farther below the text content on the left

**Comment by david-iterators** [comment]
See the updated video on Staging.  Note that the columns are misaligned on some screen widths.   https://www.loom.com/share/74845e77dffd41b2932b080c883d3863

**Comment by subaha-cob** [comment]
@david-iterators @Andrew-Iterators retest on staging please.

**Comment by david-iterators** [comment]
Verified on Staging
