### ISSUE TITLE
How to file personal Property Tax, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#238]
Brief Description
How to file personal Property Tax, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/e5b12ba3e5934568a1b826ed5cca1c61

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/departments/assessing/how-file-personal-property-tax-abatement
UAT URL: https://d8-uat.boston.gov/departments/assessing/how-file-personal-property-tax-abatement

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browsers
a)	00:03, In the Video The Production page is on the left, and the UAT Page is on the right
2)	00:12, BUG: the space between the main content and the “about page” information on the right is much wider on the Production page than the UAT page
3)	00:21, BUG: the first paragraph in the “Keep in Mind” section” (“You have three months from the date of...”) is italicized and a larger font on the UAT page than the Production page.
4)	00:34, BUG: the address in the "Keep in Mind” area is on the left column on the production page, but on the right column on the UAT page.
5)	00:40, BUG: the “CAN’T PRINT THE APPLICATION?” section of text in the Production page is within the “Keep In Mind” section”, but under the contact information collumn on the UAT page.

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
the page formatting discrepancy has been resolved
the spacing is not resolved

**Comment by david-iterators** [comment]
Resolved on Staging
