### ISSUE TITLE
Post with Image, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#239]
Brief Description
Post with Image, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/c197aadc5ec84c5db26800dc955888da

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/news/june-1-2016-boston-expands-bike-share-east-boston
UAT URL: https://d8-uat.boston.gov/news/june-1-2016-boston-expands-bike-share-east-boston

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a)	00:03, In the Video The Production page is on the left, and the UAT Page is on the right
2)	00:12, BUG: the space between the page directory and the header is smaller on the Production page than the UAT page
3)	00:21, BUG: the space to the right of the body text seperating it from the “Published By” section is wider on the Production page
a)	This makes the space for the body text narrower
4)	00:36, BUG: the spacing below the heading and above the sub-heading is greater on the Production page than the UAT page
5)	00:46, BUG: the space above the squiggly line page break is greater on the Production page than the UAT Page
6)	00:55, the spacing between paragraphs is wider on the production page than the UAT page

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
Not fixing spacing issues. 

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
This bug report is resolved

**Comment by david-iterators** [comment]
Verified on Staging
