### ISSUE TITLE
2019 08 15 Collision of header items

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#24]
Screengrab/videos (insert file names here)
2019 08 15 Collision of header items.mp4
2019 08 19, Collision of header items 2.mp4

Link
http://bostond8stg.prod.acquia-sites.com/calendar/mayor-main-trolley-tour-day-3
http://bostond8stg.prod.acquia-sites.com/public-notices/59766

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Calendar Mayor Main Trolley Tour Day 3 > Header > Head Elements

Brief Description
When the screen width is shrunk enough, the City emblem disappears; but just before that point, it obscures the “Pay and Apply” header link significantly (on the current production site, the emblem disappears before this can happen). Shrinking further, Pay and Apply collides with “Mayor Martin J. Walsh”; finally, Pay and Apply overlaps briefly with “City of Boston.”
 Steps to reproduce
1. Go to any page and narrow it until just before the emblem disappears (0:00 in video)
2. Continue narrowing until just before the Mayor link disappears (0:14)
3. Finally, continue narrowing until nearly all other header content is about to vanish (0:21)

Desired Result
Elements that become hidden do so before they overlap with other header elements.

Actual Result
Several elements collide with others before they become hidden.
- This also happens on the node 59766 (Public Notices) page, where it not only collides with other elements of the header, but the links below the header as well. This appears to be because the header icon has more space to go upwards on the Dupral 7 site than on the Dupral 8 site

[2019 08 15 Collision of header items.zip](https://github.com/CityOfBoston/Iterators/files/3505860/2019.08.15.Collision.of.header.items.zip)
[2019 08 19, Collision of header items 2.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3516327/2019.08.19.Collision.of.header.items.2.mp4.zip)

**Comment by davidrkupton** [comment]
Done

**Comment by taylor-iterators** [comment]
"Pay and Apply" remains partially obscured, but the other collision issues are fixed. Closing this.
