### ISSUE TITLE
Post without Image, Page spacing differs between Production page and UAT

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#240]
Brief Description
Post without Image, Page spacing differs between Production page and UAT

Screengrab/videos (insert file names here)
https://www.loom.com/share/c197aadc5ec84c5db26800dc955888da

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/news/june-1-2016-boston-expands-bike-share-east-boston
UAT URL: https://d8-uat.boston.gov/news/summer-safety-tips-rodent-and-pest-control

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch Production and UAT pages in Private Browsers next to each other
a.	00:03, In the Video The UAT page is on the left, and the Production Page is on the right
2)	00:10, BUG: the space between the page directory and the header is wider on the UAT page than the Production page
3)	00:17, BUG: space between header and sub-header is wider on the Production page than the UAT page
4)	00:24, BUG: The space between the body text and the “About Article” section is wider on the UAT page than the Production page
a.	BUG: the squiggly divider line above the body text is longer on the UAT page than the Production page and extends into the space between the body text and the “About Article” section
5)	00:36, BUG: the space between the paragraph title and the body text is wider on the UAT page than on the Production page.
6)	00:47, BUG: the space between the Magnifying glass and the header reading “Related Summer Safety Tips” is wider on the Production page.

Desired Result
•	Spacing and Font Size are the same

Actual Result
•	page spacing differs between Production page and UAT

**Comment by subaha-cob** [comment]
RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment]
this bug report has been resolved

**Comment by Andrew-Iterators** [comment]
Spacing has not been resolved
squiggly divider has been resolved

**Comment by david-iterators** [comment]
Verified on Staging
