### ISSUE TITLE
Ordered bullet points not properly numbered on the UAT page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#242]
Brief Description
Ordered bullet points not properly numbered on the UAT page

Screengrab/videos (insert file names here)
https://www.loom.com/share/fd030e93ba1c463e95e57981275588df

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/public-notices/64966
UAT URL: https://d8-uat.boston.gov/public-notices/64966

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browser
a)	00:01, in the video the UAT page is on the Left of the screen and the Production page is on the right.
2)	00:13, the first bullet points on screen are both correctly marked
3)	00:18, Scroll down to view the rest of the page
4)	00:24, BUG: the bullet point for “Vote 2” on the UAT page is marked as bullet point 1, while on the production page is marked as bullet point 2
5)	00:30, BUG: the above bug is present all the way down the UAT page, all marked as bullet point 1, while on the Production page is properly labeled as bullet points 1 through 6

Desired Result
•	Ordered bullet points are numbered in sequence

Actual Result
•	Ordered bullet points not properly numbered on the UAT page

**Comment by Andrew-Iterators** [comment]
This bug report has been resolved
