### ISSUE TITLE
News, Article titles clipping part of title on production page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#246]
Brief Description
News, Article titles clipping part of title on production page

Screengrab/videos (insert file names here)
https://www.loom.com/share/3dd59d5e0c96427490d7d35ee4a486eb

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/news
Stage URL: https://d8-stg.boston.gov/news

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, launch sites in private browser
a)	In the video, the Staging site is on the left and Production site is on the right
2)	00:10, Scroll down both pages so that the January 7th, 6th, and two 5ths are visible on both sites
3)	00:36, BUG: the January 7th article, titled “Mayor Wu Announces Mariangely Solis  Cervera As Chief of Equity and Inclusion” on the Staging site, but only “Mariangely Solis  Cervera As Chief of Equity and” on the Production page  (The text is clipped).   Also, the format is different.

Desired Result
•	Article links give full title on both Staging and Production Sites

Actual Result
•	Article links are displaying only partial titles on production page

**Comment by subaha-cob** [comment]
Won't fix. Staging push will be used to fix Production.
