### ISSUE TITLE
Career Center, Spacing differs between Production page and Staging page

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#248]
Brief Description
Career Center, Spacing differs between Production page and Staging page

Screengrab/videos (insert file names here)
https://www.loom.com/share/cc7dd3295180464fad1bb4dbc18d699f/

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/career-center
Staging URL: https://d8-stg.boston.gov/career-center

Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in private browser
a)	In the video the Staging page is on the left, and the production page is on the right
2)	00:16, BUG: the space after “Come work for the city of boston” is greater on the production page than the staging site
3)	00:26, BUG: The space between the body text that starts with “New application?” and the “Search for Jobs” button is greater on the Production Site than the staging site
4)	00:36, BUG: the space between the “Public Health Commission Now Hiring” body text and the blue “apply for a Job today” button is greater on the production site than the Staging site
a)	BUG: The space below the button and the “Career Center Help” header is also greater on the production page
5)	00:59, BUG: the space between the “Career Center Help” header and the body content of that section is greater on the Staging site than the Production site.
a)	BUG: the format of this section is wildly different between the production site and the staging site
i)	The “Having trouble with our career course” is a separate column on the staging site, but it is a heading text above the main content on the production page.
ii)	The title/link to each article on the staging site is formatted like a heading over the description, while on the production site they are a row heading on a table, with the description on the right
6)	01:14, BUG: the space between the divider line and the “Hear more Stories” heading is greater on the production page
7)	01:34, BUG: the spacing between the “Hear More Stories” section and the map of boston is greater on the production site than on the staging site.
a)	This is highlighted further when hovering the mouse over the bottom elements (“Tech Wizards” and “Helpful Hints”) which highlights the elements with a blue background, showing the empty space below
8)	01:55, BUG: the space between the “Benefits” header and the body content of that section is greater on the Staging site than the Production site.
a)	BUG: the format of this section is wildly different between the production site and the staging site
i)	The title/link to each article on the staging site is formatted like a heading over the description, while on the production site they are a row heading on a table, with the description on the right
ii)	The “Our employees enjoy” text and the blue “View all benefits” button is a separate column on the staging site, but they appear to be a cell in the title/link column above everything else
9)	02:08, BUG: both the white and the blue space after the “Benefits” section and before “Help with Multi-step applications” is greater on the production site than the staging site
10)	02:16, BUG: both the white and the blue space between the “Help with Multi-step applications” section and the “Additional ways to search jobs” section is greater on the production site than the staging site
11)	02:25, the space between the “additional ways to search jobs” section and the “Contact human resources” section is greater on the production site than the staging site
12)	02:39, BUG: the spacing between the phone number, email and address is greater on the production site than the staging site
a)	BUG: additionally the space between the “contact human resources” heading and the body content is greater on the production site than the staging site
b)	BUG: there is a horizontal scroll bar on the production page that is not present on the staging site
13)	02:53, BUG: the format of the “Download Brochures” section is different between the pages
a)	on the production site the downloads are arranged in a 2x3 grid
b)	on the staging site the downloads are arranged in a 1x6 grid
14)	02:57, BUG: the “Hear from Employees” section is formatted differently on the two sites
a)	On the production site the quotes are in a 4x1 grid
b)	On the Staging site, the quotes are arranged in a 2x2 grid 
15)	Testers note: The vertical Spacing issues like these are present on most of the pages

Desired Result
•	Consistent page and content formatting between the Staging site and the Production site

Actual Result
•	Several differences in the formatting of content
•	Various differences in vertical spacing between the staging and production sites

**Comment by subaha-cob** [comment]
Won't fix. Looks better on stage.
