### ISSUE TITLE
Secondary Header has wrong title for a link

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#25]
Screengrab/videos (insert file names here)
2019 08 15, Secondary Header has wrong title for a link.mp4
[2019 08 15, Secondary Header has wrong title for a link.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3505866/2019.08.15.Secondary.Header.has.wrong.title.for.a.link.mp4.zip)

Link
https://boston.gov/node/45351

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Drupal 7 node 45351 page > Secondary Header > 2018 winners link

Brief Description
The Secondary Header on the Drupal 7 page has a link to 2018 winners, but when clicked on it goes to the 2019 winners section of the page

Steps to reproduce
1. Open the Drupal 7 link for node 45351 page
2. Scroll down until the Secondary Header is visible
3. Click 2018 winners

Desired Result
•	The section that the link goes to is named 2018 Winners

Actual Result
•	The section that the link goes to is named 2019 Winners

**Comment by davidrkupton** [comment]
Nice catch !
But I think this is content related based on slightly outdated info on staging site.  
The secondary title text is input by the content editor and is different to the in-page title.  This page has been recycled from the same event in 2018 so I suspect the navigation title was initially missed and then fixed later.
I cannot replicate locally - lets see if the issue persists after we make this Thursdays updates.

**Comment by ollie-iterators** [comment]
It appears the the problem was fixed by the update on Thursday
