### ISSUE TITLE
2019 08 15 Pay and Apply duplicate

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#26]
Screengrab/videos (insert file names here)
2019 08 15 Pay and Apply duplicate.png

Link
http://bostond8stg.prod.acquia-sites.com/calendar/mayor-main-trolley-tour-day-3

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Calendar Mayor Main Trolley Tour Day 3 > Header > Pay and Apply

Brief Description
“Pay and Apply” appears twice in the header. Only the first instance is a functional link.
 Steps to reproduce
1. Go to any page and look at the header

Desired Result
Header does not repeat itself.

Actual Result
There is a second instance of Pay and Apply.

![2019 08 15 Pay and Apply duplicate](https://user-images.githubusercontent.com/49662945/63102176-9af7ea80-bf48-11e9-94c1-d0c636808822.png)

**Comment by davidrkupton** [comment]
There are 2 entries in the D7 database.

```SELECT * FROM menu_links WHERE link_title='Pay and apply';```

Seems that there are 2 links for this secondary menu: `/node/32906` and `/node/3256`.
However only 32906 is a valid link.
Have disabled the bad link in D7 and so the bad link is going to be migrated but will be disabled next release.

**Comment by taylor-iterators** [comment]
For me the issue persists. Reassigned. See attached screenshot, taken after clearing browser data and restarting computer.
![2019 08 23 Pay and Apply duplicate](https://user-images.githubusercontent.com/49662945/63613508-ecd6eb00-c5ae-11e9-9d97-5b8def6dcecd.png)

**Comment by taylor-iterators** [comment]
Issue has been resolved. Closing this.
