### ISSUE TITLE
Scrolling stops after using side menu

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#28]
Screengrab/videos (insert file names here)
2019 08 15, Scrolling stops after using side menu.mp4
>>>>> Note, Github registered an error because the file was was greater than 10 MB.  The file is not yet uploaded.

Link and Node #
http://bostond8stg.prod.acquia-sites.com/calendar/mayor-main-trolley-tour-day-3
Node:  45361

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Computer > macOS 10.14.6 > Chrome  76.0.3809.100 (Official Build) (64-bit)

Brief Description
The page will not respond to scrolling with the mouse after a sequence using the side menu.  Note that this occurs on the boston.gov website also.
 Steps to reproduce
1. 0:00 Go to the link shown above, observe that the window can be scrolled vertically
2. 0:08 Click on the Side menu to expand, observer that the window can NOT be scrolled when the menu is active
3.  0:14. Close the side menu, and the window can be scrolled again
4.  0:20, Open the side menu and click on a link, such as “Guides to Boston”
5.  0:25, Press the back button on the browser to return to the original page, notice that the side menu is still open.  Notice that the window can be scrolled
6.  0:32, Close the side menu, notice that the window can NOT be scrolled
7.  0:43, Refresh the page on the browser, now the window can be scrolled again.

Desired Result
Window can always be scrolled.

Actual Result
Window cannot be scrolled after using the side menu bar with the sequence discussed above.

**Comment by david-iterators** [comment]
This is a link to the screen recording which is stored in Google Drive to to the size of the movie:
https://drive.google.com/open?id=1sQ1YGiEiw6SW1YxxLG_7lza7ZKVjBCcb

**Comment by davidrkupton** [comment]
Done

**Comment by davidrkupton** [comment]
Was a D7 feature/issue as well, but removed because it is poor user-experience and not common to lock a page for no reason other than a menu extending.

**Comment by ollie-iterators** [comment]
This has been fixed
