### ISSUE TITLE
2019 08 15 Personal page omitting job title

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#30]
Screengrab/videos (insert file names here)
2019 08 15 Personal page omitting job title.mp4

Link
http://bostond8stg.prod.acquia-sites.com/city-council/mark-ciommo

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Mark Ciommo personal page > Body > Subtitle

Brief Description
On the current version of this page (https://www.boston.gov/departments/city-council/mark-ciommo), Mr. Ciommo’s name is subtitled “City Councilor, District 9.” On the new staging version, that’s truncated to merely “District 9.” Perhaps “City Councilor” is a separate field, and the comma separation caused it to go unread?
 Steps to reproduce
1.	Go to Mark Ciommo’s page on both production and staging sites
2.	Focus on the top of the page’s body, just below his name

Desired Result
The two pages display identical or near-identical content.

Actual Result
The man’s position is omitted from the staging version of the page.

[2019 08 15 Personal page omitting job title.zip](https://github.com/CityOfBoston/Iterators/files/3506017/2019.08.15.Personal.page.omitting.job.title.zip)

**Comment by davidrkupton** [comment]
Fixed.

**Comment by taylor-iterators** [comment]
Issue is resolved. Closing this.
