### ISSUE TITLE
2019 08 15 Elected, Party display changes

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#31]
Screengrab/videos (insert file names here)
2019 08 15 Elected, Party display changes.mp4

Link
http://bostond8stg.prod.acquia-sites.com/city-council/mark-ciommo

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Mark Ciommo personal page > Body > Subtitle

Brief Description
On the current version of this page (https://www.boston.gov/departments/city-council/mark-ciommo), the fields below Mr. Ciommo’s profile include “Elected:” and “Party:”, whereas the new staging page uses “Year Elected” and “Political Party” instead. This is a very minor and perhaps intentional difference.
 Steps to reproduce
1.	Go to Mark Ciommo’s page on both production and staging sites
2.	Focus on the text fields below his photo

Desired Result
The two pages display identical or near-identical content.

Actual Result
The staging site uses slightly more in-depth labels for some fields.

[2019 08 15 Elected, Party display changes.zip](https://github.com/CityOfBoston/Iterators/files/3506061/2019.08.15.Elected.Party.display.changes.zip)

**Comment by davidrkupton** [comment]
Nice catch!
Done.

**Comment by taylor-iterators** [comment]
This issue is fixed, and I'm closing it. However, in reviewing the page I found another discrepancy between the Drupal 7 and 8 versions; see #81: City Council pages missing Committe Involvement.
