### ISSUE TITLE
Footer links get scrunched together at a certain width

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#32]
Screengrab/videos (insert file names here)
2019 08 15, Footer links get scrunched together at a certain width.mp4
[2019 08 15, Footer links get scrunched together at a certain width.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3506177/2019.08.15.Footer.links.get.scrunched.together.at.a.certain.width.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/45361 

Dupral 7 Link:
•	https://boston.gov/node/45361 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Dupral 7 and 8 pages > footer >footer links

Brief Description
The footer links get 

Steps to reproduce
1. Go to the Dupral 7 and 8 pages
2. Make the pages the minimum width they can be
3. Slowly expand the width of the pages and see how the footer elements react

Desired Result
•	The footer elements are spread out well during the expansion of the site

Actual Result
•	At a certain point in the expansion, the footer elements get scrunched together

**Comment by davidrkupton** [comment]
OK This occurs on both D7 and D8.
