### ISSUE TITLE
2019 08 15 Different path info given in personal page.

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#33]
Screengrab/videos (insert file names here)
2019 08 15 Different path info given in personal page.mp4

Link
http://bostond8stg.prod.acquia-sites.com/city-council/mark-ciommo

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Mark Ciommo personal page > Body > Subtitle

Brief Description
On the production version of this page (https://www.boston.gov/departments/city-council/mark-ciommo), the path described just below the header is Home > Departments > City Council > Mark Ciommo. Compare to the staging site, which is Home > City-Council > Mark Ciommo (and note the hyphenation of city-council, not on the production site). The user can access Departments indirectly by clicking City-Council first. 
 Steps to reproduce
1.	Go to Mark Ciommo’s page on both production and staging sites
2.	Focus on the site path just below the header

Desired Result
The two pages display identical or near-identical content.

Actual Result
The staging site says “City-Council” rather than “City Council” and omits “Departments” altogether.

[2019 08 15 Different path info given in personal page.zip](https://github.com/CityOfBoston/Iterators/files/3506188/2019.08.15.Different.path.info.given.in.personal.page.zip)

**Comment by davidrkupton** [comment]
Done.
This was fixed by release last Thursday (August 22nd)

**Comment by taylor-iterators** [comment]
Verified. Closing this one.
