### ISSUE TITLE
Footer moves downward when expanding the width of the page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#34]
Screengrab/videos (insert file names here)
2019 08 15, Footer moves downward when expanding the width of the page.mp4
[2019 08 15, Footer moves downward when expanding the width of the page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3506251/2019.08.15.Footer.moves.downward.when.expanding.the.width.of.the.page.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/45361 

Dupral 7 Link:
•	https://boston.gov/node/45361 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Dupral 7 and 8 pages > Footer > width of the page

Brief Description
The footer of the website goes downward as the page is expanded

Steps to reproduce
1. Go to the Dupral 7 and 8 pages
2. Make the pages be the minimum width they can be
3. Slowly expand the pages and see if the footer reacts how it is expected to react

Desired Result
•	The footer only goes downward as the page becomes less wide

Actual Result
•	The footer goes downward as the page is expanded also

**Comment by mmcgowanBOS** [comment]
Having trouble seeing this as an issue. This may have already been fixed.

**Comment by davidrkupton** [comment]
Not on Chrome ...
Did we check on Safari ?

**Comment by ollie-iterators** [comment]
This does happen on Safari still. 
[2019 08 23, Footer moves downward when expanding the width of the page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3535091/2019.08.23.Footer.moves.downward.when.expanding.the.width.of.the.page.mp4.zip)

**Comment by mmcgowanBOS** [comment]
I'm having trouble understanding how this is a bug? This seems like normal behavior to me.
