### ISSUE TITLE
2019 08 15 Broken News search function

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#36]
Screengrab/videos (insert file names here)
2019 08 15 Broken News search function.mp4

Link
http://bostond8stg.prod.acquia-sites.com/latest-city-boston-news

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
News main page > Search/filter fields > Author

Brief Description
On the Latest News page, if the user selects Author among the search/filter options and enters an author known to have contributed to one or more press releases listed, then clicks Apply, the site responds with “NO POSTS FOUND.” Two red X buttons appear, one each on the left and right side of the search bar, as well as a refresh button. None of these three are functional, and refreshing the page does not resolve the situation; as such the user cannot proceed without re-entering the URL or navigating to an unrelated corner of the site, and this should be considered a high-priority bug.
Note: this was also tested on an iPad running Safari, with identical results.

 Steps to reproduce
1.	Go to Latest News page on both the Drupal 7 and Drupal 8 versions of the site
2.	On D7 site, scroll down until you reach an article that also appears in D8, since the two are not quite in synch (this test used “City seeks creative ideas for Upham’s Corner Arts and Innovation District”)
3.	Open that article, copy the publisher (here, “Economic Development”) (0:08 in video)
4.	In D8 site, open Author field and select paste, then Apply (0:15)

Desired Result
Since at least one item is known to have that author, there will be relevant results returned.

Actual Result
No results found; additionally, new elements of the page appear which do not function, and it is difficult to return to News from this point.

[2019 08 15 Broken News search function.zip](https://github.com/CityOfBoston/Iterators/files/3506740/2019.08.15.Broken.News.search.function.zip)

**Comment by davidrkupton** [comment]
Done.

**Comment by taylor-iterators** [comment]
Search function is now behaving itself. Closing this.
