### ISSUE TITLE
2019 08 15 News subheader only visible with narrow page

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#38]
Screengrab/videos (insert file names here)
2019 08 15 News subheader only visible with narrow page.mp4

Link
http://bostond8stg.prod.acquia-sites.com/latest-city-boston-news

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
News main page > Body > Subheading

Brief Description
On the Latest News page, the Drupal 7 version prominently displays “LATEST CITY OF BOSTON NEWS.” This text is coded into the Drupal 8 site, but at least on a large Mac desktop it can only be seen at all when the window is shrunk to under half of the screen’s width, and does not become completely visible and legible until shrunk to roughly a quarter of the screen size.
Note: this seems to hold for a number of other pages on the site, e.g Events (http://bostond8stg.prod.acquia-sites.com/events)

 Steps to reproduce
1.	Go to Latest News page
2.	Enlarge the window width-wise until it takes up the entire screen
3.	Now shrink the window by length until it is quite skinny
Desired Result
Altering window width does not conceal or hide any important information.

Actual Result
The subheading, clearly intended to be the most prominent text on the whole page, is only visible on narrow screens; this tester did not notice it at all until after performing several other tests on this page and stumbling upon it.

[2019 08 15 News subheader only visible with narrow page.zip](https://github.com/CityOfBoston/Iterators/files/3506937/2019.08.15.News.subheader.only.visible.with.narrow.page.zip)

**Comment by davidrkupton** [comment]
Cannot reproduce on Chrome.
@mmcgowanBOS can you try on safari ?

**Comment by mmcgowanBOS** [comment]
I can confirm that I'm seeing this on Chrom and Safari on Mac OSX (Sierra
![Screen Shot 2019-08-26 at 1 47 14 PM](https://user-images.githubusercontent.com/44584567/63710874-2ce4da80-c808-11e9-8e54-b787d6be305d.png)
<img width="875" alt="Screen Shot 2019-08-26 at 1 47 32 PM" src="https://user-images.githubusercontent.com/44584567/63710878-2f473480-c808-11e9-8b95-7d52e3531fc2.png">

)

**Comment by davidrkupton** [comment]
I think a Duplicate of #37 .

**Comment by taylor-iterators** [comment]
Fixed. Closing this.
