### ISSUE TITLE
Other Landing page has links that do not go to staging site on Drupal 8 site

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#40]
Screengrab/videos (insert file names here)
2019 08 16, Other Landing page has links that do not go to staging site on Dupral 8 site
[2019 08 16, Other Landing page has links that do not go to staging site on Dupral 8 site.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3510875/2019.08.16.Other.Landing.page.has.links.that.do.not.go.to.staging.site.on.Dupral.8.site.mp4.zip)

Link and Node #
Dupral 8 Link:
• http://bostond8stg.prod.acquia-sites.com/node/19261

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Other Landing Page > Elements > Links

Brief Description
Some links on the Other landing page do not go to the Dupral 8 site on the Dupral 8 site

Steps to reproduce
1. Go to http://bostond8stg.prod.acquia-sites.com/node/19261
2. Check out the links on the page to see where they go to

Desired Result
• All the links go to the Dupral 8 site

Actual Result
• Not all the links go to the Dupral 8 site
o	Insurance
o	Work and life benefits
o	Savings and investments

**Comment by davidrkupton** [comment]
Essentially the same comment as #33 .
These links are content which have been entered manually by content-editors.  The links will join up properly when this site is put live and is hosted on www.boston.gov.

**Comment by davidrkupton** [comment]
Marking as fixed as the link will go to boston.gov when this site is hosted at boston.gov.
