### ISSUE TITLE
2019 08 16 Events section missing from Transportation page

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#41]
Screengrab/videos (insert file names here)
2019 08 16 Events section missing from Transportation page.mp4

Link
http://bostond8stg.prod.acquia-sites.com/departments/transportation

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Transportation main page > Body > Link cloud

Brief Description
On the Transportation page, there is a cloud of links near the top that direct to other sections further down. One of these, Events, is present in the Drupal 7 but not the D8 site; scrolling down or searching “events” reveals that that entire section is missing from the D8 build.

 Steps to reproduce
1.	Go to the Transportation page on both D7 and D8 sites
2.	On D7, click on Events, which takes you to the Upcoming Events section
3.	Attempt to find that page on D8

Desired Result
Whether titled Current Events or not, the same essential content under that section of the D7 site is also available on the D8 version.

Actual Result No such section can be found.

[2019 08 16 Events section missing from Transportation page.zip](https://github.com/CityOfBoston/Iterators/files/3510903/2019.08.16.Events.section.missing.from.Transportation.page.zip)

**Comment by jimafisk** [comment]
The `events_and_notices` paragraph is missing completely on `/node/121`:

![component_missing_entirely](https://user-images.githubusercontent.com/5913244/63285340-79b63780-c283-11e9-87f9-38243d5be0c6.png)

**Comment by taylor-iterators** [comment]
Events section is now visible. It lists no upcoming events, but that's presumably because of the current database inconsistency. Closing this.
