### ISSUE TITLE
Resources link not opening in separate tab on Dupral 8 page for Public Notices page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#45]
Screengrab/videos (insert file names here)
2019 08 19, Resources link not opening in separate tab on Dupral 8 page.mp4

Link and Node #
Dupral 8 Link:
- http://bostond8stg.prod.acquia-sites.com/node/59766 
- http://bostond8stg.prod.acquia-sites.com/node/48276

Dupral 7 Link:
- https://boston.gov/node/59766 
- https://boston.gov/node/48276

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 76

Section
(Page > Area > Element)
Public Notices > Event > Resources link

Brief Description
The resources link is not opening in a new tab on the Dupral 8 page

Steps to reproduce
1. Go to Dupral 7 and Dupral 8 pages for node 59766 or 48276 page (Bug is about node 59766 page)
2. Click on the resources link to see how they react to being clicked on

Desired Result
•	There are no differences in how the pages behave when being clicked on the Dupral 8 and Dupral 7 page

Actual Result
•	On the Dupral 8 page the resources link does not open in a new tab

**Comment by davidrkupton** [comment]
Done.
