### ISSUE TITLE
2019 08 19 Meet the Commissioner absent from Transportation

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#46]
Screengrab/videos (insert file names here)
2019 08 19 Meet the Commissioner absent from Transportation.png

Link
http://bostond8stg.prod.acquia-sites.com/departments/transportation

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Transportation main page > Body > Meet the Commissioner

Brief Description
On the Transportation page, at the very bottom of the body on Drupal 7 version is a section titled “Meet the Commissioner”, featuring a portrait of Mr. Gregory T. Rooney. This section is entirely absent from the Drupal 8 version of the site.
 Steps to reproduce
1.	Go to the Transportation page
2.	Scroll down to bottom of page

Desired Result
The last section is Meet the Commissioner, in accordance with the D7 version of the site.

Actual Result Meet the Commissioner is omitted entirely.

<img width="2556" alt="2019 08 19 Meet the Commissioner absent from Transportation" src="https://user-images.githubusercontent.com/49662945/63273275-af4f2680-c26b-11e9-8350-bc220fe9fee8.png">

**Comment by davidrkupton** [comment]
OK, so I believe that the `meet the commissioner` - `grid-of-people` component  was added on August-19.  The stg environment (and dev) are using a database captured on 18-Aug.  
Manually added the component locally and it displayed OK.
Hopefully this component will migrate on Thursday.

**Comment by taylor-iterators** [comment]
Verified. Closing this one.
