### ISSUE TITLE
On the How To page the Emergency Medical Services Contact link goes to an error page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#47]
Screengrab/videos (insert file names here)
2019 08 19, Emergency Medical Services link bad.mp4
[2019 08 19, Emergency Medical Services link bad.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3516913/2019.08.19.Emergency.Medical.Services.link.bad.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/3606 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Galaxy Tablet A > Android 6.0.1 > Chrome 76

Section
(Page > Area > Element)
How To page > Contact section > Emergency Medical Services Link

Brief Description
Emergency Medical Services Link goes to a bad page on the Dupral 8 site

Steps to reproduce
1. Go to the Dupral 8 site for node 3606
2. Go to the Contact section of the page
3. Click Emergency Medical Services Link

Desired Result
•	The link goes to the Emergency Medical Services page

Actual Result
•	The link goes to a page with errors on it

**Comment by taylor-iterators** [comment]
There is an identical link on the same part of this page: http://bostond8stg.prod.acquia-sites.com/emergency-medical-services/how-apply-ems-special-event-permit
It, of course, is also broken.

**Comment by davidrkupton** [comment]
This looks OK now.
I think it was fixed with release 22 August.

**Comment by ollie-iterators** [comment]
This has been fixed
