### ISSUE TITLE
On How To page, the Learn more about hands-on CPR link does not open in a new tab

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#48]
Screengrab/videos (insert file names here)
2019 08 19, CPR link does not open in new tab on Dupral 8 page.mp4
[2019 08 19, CPR link does not open in new tab on Dupral 8 page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3516935/2019.08.19.CPR.link.does.not.open.in.new.tab.on.Dupral.8.page.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/3606 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Galaxy Tablet A > Android 6.0.1 > Chrome 76

Section
(Page > Area > Element)
How To page > Contact section > Learn more about hands-only CPR link

Brief Description
Learn more about hands-only CPR link does not open in a separate tab

Steps to reproduce
1. Go to the Dupral 8 site for node 3606
2. Go to the Learn about Hands-Only CPR section
3. Click Learn more about hands-only CPR link

Desired Result
•	The link opens in a new tab

Actual Result
•	The link does not open in a new tab

**Comment by davidrkupton** [comment]
This is the same behaviour as on d7:
https://www.boston.gov/departments/emergency-medical-services/cpr-training

**Comment by mmcgowanBOS** [comment]
Going to close issue for now. This is happening in D7 as well. This is a content related issue that a content owner  can / should update.
