### ISSUE TITLE
Wrong colors / order for featured_topics Paragraph

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#49]
Screengrab/videos (insert file names here)
2019 08 19 Visiting Boston- Recommended Resources bugs.png

Link
http://bostond8stg.prod.acquia-sites.com/visiting-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Visiting Boston page > Recommended Resources > Guide list

Brief Description
On the Visiting Boston page, below Recommended Resources towards the bottom is a list of four Guide links. On the current Drupal 7 site, there are labeled 1-4 in order and are color coded in blue, black, red, and black again; compare this to the Drupal 8 build where they are black, blue, blue again, and black again, and are labeled 2, 1, 1, 2. Note also that “Uncovering Boston’s History” is jumbled with what seems to be ASCII code.
The links themselves are fully functional and line up with those on the D7 site; this is entirely an aesthetic issue.
 Steps to reproduce
1.	Go to the Visiting Boston page
2.	Scroll down to just under Recommended Resources
3.	Observe the Guide list

Desired Result
The items listed are in alternating colors and are labeled with suitable numbers.

Actual Result Numerical ordering is nonsensical, same-colored elements border one another, and there is low-level code in one element’s title.

<img width="2544" alt="2019 08 19 Visiting Boston- Recommended Resources bugs" src="https://user-images.githubusercontent.com/49662945/63290781-30201980-c290-11e9-8932-262f29200cf9.png">

**Comment by ollie-iterators** [comment]
This also happens on node 7536

**Comment by davidrkupton** [comment]
Done.
I think this was this was fixed on 22/Aug.

**Comment by taylor-iterators** [comment]
Can't be tested at the moment- the link prompts an Error 403.

**Comment by david-iterators** [comment]
For Reference this is node 6661

**Comment by taylor-iterators** [comment]
The layout has changed a bit since this issue was posted, and it is more presentable, but things still aren't quite right. See attached image.
![2019 09 05 Departments You May Need](https://user-images.githubusercontent.com/49662945/64353482-d461ca00-cfcb-11e9-8821-d90b0d82c9c6.png)

**Comment by jimafisk** [comment]
This still seems to be an issue: http://bostond8stg.prod.acquia-sites.com/visiting-boston

I'm taking a look.

**Comment by jimafisk** [comment]
This is fixed on dev: http://bostond8dev.prod.acquia-sites.com/visiting-boston

**Comment by jimafisk** [comment]
Still broken on dev, checkout the homepage: http://bostond8dev.prod.acquia-sites.com/

![order](https://user-images.githubusercontent.com/5913244/65693691-b6274100-e042-11e9-8ee6-118e121813f2.png)

**Comment by jimafisk** [comment]
Ok so now that I'm moving back to tackle this issue it appears fixed on the homepage again...
http://bostond8dev.prod.acquia-sites.com/visiting-boston is still broken though.

They seem to work inconsistently, so I think the count logic is off. Taking a look.
