### ISSUE TITLE
Uncovering Boston's History image missing

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#50]
Screengrab/videos (insert file names here)
2019 08 19 Uncovering Boston's History image missing.png

Link
http://bostond8stg.prod.acquia-sites.com/visiting-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Visiting Boston page > Body > Uncovering Boston’s History

Brief Description
On the Drupal 7 version of the Visiting Boston page, there is a backdrop photo of a historic cemetery. The Drupal 8 version omits this entirely and has only whitespace for a backdrop.
 Steps to reproduce
1.	Go to the Visiting Boston page
2.	Scroll down to Uncovering Boston’s History

Desired Result
The background image is comparable to the one on the D7 build.

Actual Result There is no background image at all.

<img width="2557" alt="2019 08 19 Uncovering Boston's History image missing" src="https://user-images.githubusercontent.com/49662945/63291862-678fc580-c292-11e9-8093-308b19850d3b.png">

**Comment by mmcgowanBOS** [comment]
Looks like this may already be fixed. Can't see the issue.

**Comment by davidrkupton** [comment]
Cleared cache and this now shows on STAGE and DEV.

**Comment by taylor-iterators** [comment]
Can't be tested at the moment- the link prompts an Error 403.

**Comment by david-iterators** [comment]
For Reference, this is node 6661 and is showing a 403 error.  See #49 for a bug on this same page.

**Comment by mmcgowanBOS** [comment]
Should be fixed on staging.

**Comment by ollie-iterators** [comment]
This has been fixed
