### ISSUE TITLE
Event Title collides with the event information on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#51]
Screengrab/videos (insert file names here)
2019 08 19, Event header collides with Event information.mp4
[2019 08 19, Event header collides with Event information.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3517310/2019.08.19.Event.header.collides.with.Event.information.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/61556 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 76

Section
(Page > Area > Element)
Event page > Event content > Event information and Event Title

Brief Description
The Title for the Event collides with the Event information at a certain width on the Dupral 8 page

Steps to reproduce
1. Go to the Dupral 8 page for node 61556
2. Make the page less wide and look for how the Event title responds to the decrease in width for the page

Desired Result
•	The Event title does not collide with any content

Actual Result
•	The Event title collides with the Event information at certain widths

**Comment by davidrkupton** [comment]
Exists on D7. 
Similar to #39 - have not made any resolution, I think we just have to accept this as-is since it is the same as D7.

**Comment by reillyzlab** [comment]
CLosing
