### ISSUE TITLE
Cityscore text cutoff

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#52]
Screengrab/videos (insert file names here)
2019 08 19 Cityscore text cutoff.jpg

Link
http://bostond8stg.prod.acquia-sites.com/innovation-and-technology/cityscore
Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Chrome 76

Section
(Page > Area > Element)
Cityscore page > Body > Top paragraph 

Brief Description
The top of the Cityscore page has a number of issues. The first two are Windows-specific:
On both the Drupal 7 and Drupal 8 versions of this page, the text of the first line of the description paragraph under “CITYSCORE” is cut off. Also, just below that paragraph there is an element labeled “Program Menu” on D7; on D8 this is instead “Page Sections.”
The other two issues are not OS-specific:
The D7 page has a large relevant image just below the header; this is absent on D8.
Between that space and the title “CITYSCORE” is a web path- it lists Home > Cityscore on D7 but Home > Innovation-And-Technology > Cityscore on D8.
 Steps to reproduce
1.	Go to the Cityscore page

Desired Result
Content and functionality are near-identical between D7 and D8 pages, and everything is clean and legible.

Actual Result There are a number of discrepancies between the two builds, and both of them suffer from text cutoff on Windows-Chrome configuration.

![2019 08 19 Cityscore text cutoff](https://user-images.githubusercontent.com/49662945/63294247-d7ed1580-c297-11e9-86f1-569a79d6101d.jpg)

**Comment by davidrkupton** [comment]
Accepted.

**Comment by davidrkupton** [comment]
Done.
There are residual issues with related content and case studies not showing up.  Both of these are possibly related to the migration failing when the cityscore was not available.

**Comment by taylor-iterators** [comment]
Verified. Closing this.
