### ISSUE TITLE
Search function absent from Public Notices

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#54]
Screengrab/videos (insert file names here)
2019 08 20 Search function absent from Public Notices.jpg

Link
http://bostond8stg.prod.acquia-sites.com/public-notices

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Internet Explorer 11

Section
(Page > Area > Element)
Public Notices > Body > Search function

Brief Description
On the Drupal 7 Public Notices page, there is a search/filter function near the top of the page. When this tester first opened the Drupal 8 page, the search function was missing entirely. This could not be reproduced on the Windows/Explorer configuration or on Mac desktop/Chrome, but it can reliably be reproduced on an iPhone.
Note: on further inspection this is just a matter of screen width; it's easily amended on a computer, but even on the landscape orientation the search does not appear on the iPhone. Consider this a mobile bug.

 Steps to reproduce
1.	Go to the Public Notices page

Desired Result
If it’s not exactly where it appears in the D7 build, the search/filter function appears elsewhere on the page.

Actual Result Search is absent from the D8 page entirely.

![2019 08 20 Search function absent from Public Notices](https://user-images.githubusercontent.com/49662945/63353258-7927aa80-c330-11e9-808e-1ef417870afa.jpg)

**Comment by davidrkupton** [comment]
This issue is:
**Search text box disapears when screen-size dropped below 980px (i.e. on tablet and mobile breakpoints)**

**Comment by mmcgowanBOS** [comment]
link #50

**Comment by taylor-iterators** [comment]
Issue is resolved. Search function is present and seems to work properly.
