### ISSUE TITLE
Guides missing options

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#55]
Screengrab/videos (insert file names here)
2019 08 20 Guides missing options.jpg

Link
http://bostond8stg.prod.acquia-sites.com/guides

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Internet Explorer 11

Section
(Page > Area > Element)
Guides > Body > Options below guide titles

Brief Description
On the Drupal 7 Guides page, each specific Guide panel includes a list of four links to specific segments of that guide’s page. For instance, “Affordable Housing in Boston” is followed by the links “Where to start”, “Explainer”, “Types of housing”, and “See 12 more.” All this is missing from the Drupal 8 guide panels (this is consistent across device/browser orientations and window dimensions). In both D7 and D8 each guide’s title is itself a link, so all pages are still accessible, but a great deal of detail is lost.
 Steps to reproduce
1.	Go to the Guides page
2.	Scroll down and look at specific guide panels

Desired Result
For each guide panel, the same links are available as are present in the D7 panels.

Actual Result The lists of links are absent from the D8 page entirely.

![2019 08 20 Guides missing options](https://user-images.githubusercontent.com/49662945/63355417-16d0a900-c334-11e9-910b-f1e27b7bb80a.jpg)

**Comment by davidrkupton** [comment]
Fixed layout issues. 
However content is still missing due to unpublished nodes state which needs to be addressed.

**Comment by taylor-iterators** [comment]
The D8 page is now nearly identical to the D7. Closing this.
