### ISSUE TITLE
Government page- City Council profile pics broken

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#56]
Screengrab/videos (insert file names here)
2019 08 20 Government page- City Council profile pics broken.jpg

Link
http://bostond8stg.prod.acquia-sites.com/311/city-boston-government

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Internet Explorer 11

Section
(Page > Area > Element)
City of Boston Government > City Council > Individual profiles

Brief Description
The City of Boston Government page features a City Council section with names, contact information, and photos for each Councilor. On Drupal 7 these images load just fine, but on Druapl 8 they are all broken. Interestingly, further down the page is a Cabinets section, where photos of relevant individuals load without incident.
 Steps to reproduce
1.	Go to the City of Boston Government page
2.	Scroll down to City Council and look at panels describing individual members

Desired Result
Photographs of individuals are present.

Actual Result Photographs fail to load.

![2019 08 20 Government page- City Council profile pics broken](https://user-images.githubusercontent.com/49662945/63356952-a9724780-c336-11e9-8511-2e8b23c97816.jpg)

**Comment by mmcgowanBOS** [comment]
This seems to be fixed on staging.

**Comment by taylor-iterators** [comment]
The page is not currently available. Reassigning this.

**Comment by reillyzlab** [comment]
resolved so closing
