### ISSUE TITLE
Chris Osgood profile photo discrepancy

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#57]
Screengrab/videos (insert file names here)
2019 08 20 Chris Osgood profile photo discrepancy.jpg

Link
http://bostond8stg.prod.acquia-sites.com/311/city-boston-government
http://bostond8stg.prod.acquia-sites.com/node/3311

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Internet Explorer 11

Section
(Page > Area > Element)
City of Boston Government > Cabinets > Chris Osgood profile picture

Brief Description
The City of Boston Government page features a Cabinets section, containing descriptions of various cabinets, most of which come with a profile of a key individual involved. The individual shown for “Streets”, Chris Osgood, has a very different photo in the Drupal 7 and Drupal 8 sites. A quick web search indicates that both do portray Mr. Osgood- D8 uses his LinkedIn profile image- but the discrepancy is worth reporting.

 Steps to reproduce
1.	Go to the City of Boston Government page
2.	Scroll down to Cabinets > Streets

Desired Result
Chris Osgood’s profile photo is the same across D7 and D8.

Actual Result The two photos are radically different. 

![2019 08 20 Chris Osgood profile photo discrepancy](https://user-images.githubusercontent.com/49662945/63359222-6023f700-c33a-11e9-8349-3872c1895138.jpg)

**Comment by mmcgowanBOS** [comment]
This seems to be fixed on staging.

**Comment by ollie-iterators** [comment]
The node 3311 page is not able to be seen on the bostond8stg site

**Comment by taylor-iterators** [comment]
The page is still down on D8 ("Looks like this page went overboard"). Reassigning this.

**Comment by reillyzlab** [comment]
Resolved so closing
