### ISSUE TITLE
Place Profile page on Dupral 8 does not have Address section

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#58]
Screengrab/videos (insert file names here)
2019 08 20, Place Profile page on Dupral 8 does not have Address section
[2019 08 20, Place Profile page on Dupral 8 does not have Address section.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3521421/2019.08.20.Place.Profile.page.on.Dupral.8.does.not.have.Address.section.mp4.zip)
.mp4

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/4286 

Dupral 7 Link:
•	https://boston.gov/node/4286 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Place Profile > Event section > Address element

Brief Description
The Place Profile page on Dupral 8 sites does not have the Address element for the Event section

Steps to reproduce
1. Open the Dupral 7 and Dupral 8 pages for node 42866
2. Check out both Event sections and compare the elements

Desired Result
•	Both pages have the same elements

Actual Result
•	The Dupral 8 page does not have the Address element in the Event section of the page

**Comment by mmcgowanBOS** [comment]
I also noticed that the h1 Title on this page is not showing (Mac - Chrome). See screen shot attached.
![Screen Shot 2019-08-26 at 3 33 36 PM](https://user-images.githubusercontent.com/44584567/63717773-f8c4e600-c816-11e9-99bb-fd43d34be36b.png)

**Comment by jimafisk** [comment]
Yeah it's strange, both the title and the address were missing for me, then randomly appeared:

![address](https://user-images.githubusercontent.com/5913244/63780212-bef6ec80-c8b5-11e9-84de-2159cb7e0b8e.png)

I think it may have to do with the fact that I edited node (but didn't save anything). @mmcgowanBOS if you simply go to the edit screen then reload, does it clear this up on your end as well?

**Comment by jimafisk** [comment]
Nevermind! Pulling the most recent develop fixed the title with:
```
.desktop-100,
.desktop-100.node-listing-page {
  position:relative;
}
``` 
(commit c727f3dd9bd16c6e941d2fb3d4182162226a80b1)
