### ISSUE TITLE
Contact Info Return Value does not agree with validation source "Abandoned"-A100484

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#6]
Screengrab/videos (insert file names here)
2019 9 27, Contact Info Return Value does not agree with source
[2019 9 27, Contact Info Return Value does not agree with source.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3443659/2019.9.27.Contact.Info.Return.Value.does.not.agree.with.source.mp4.zip)
.mp4

Link
https://permit-finder.digital-staging.boston.gov/permit?id=A939804

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 75

Section
(Page > Area > Element)
Permit Info Page > Have Questions Section > Contact Info

Brief Description
The Contact Info section in the Staging page has information in it, while the validation section does not have any information in that section

Steps to reproduce
1. Go to the permit finder staging page (https://permit-finder.digital-staging.boston.gov/)
2. Search for Permit A176185
3. Look at the Contact Info section

Desired Result
• There is no information in the Contact Info section

Actual Result
• There is information in the Contact Info section
o	The information is ‘Call the Boston Inspectional Services Department at (617) 635-5300.’

Note: Production consistent with validation CSV

**Comment by TomM-IT** [comment]
We cross checked this in Prod, one thought was it may be a residual contact tag that did not get cleared out.

Tom

**Comment by reillyzlab** [comment]
Believe this is resolved. Contact info is showing up.
