### ISSUE TITLE
BCYF Mirabella Pool missing background image

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#60]
Screengrab/videos (insert file names here)
2019 08 20 BCYF Mirabella Pool missing background image.jpg

Link
http://bostond8stg.prod.acquia-sites.com/community-centers/bcyf-mirabella-pool
http://bostond8stg.prod.acquia-sites.com/node/4266

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Internet Explorer 11

Section
(Page > Area > Element)
BCYF Mirabella Pool > Top of page > Background image

Brief Description
The Drupal 7 version of the Mirabella Pool page has a large photo of said pool as the background of the top of the page. This image does not appear on the Drupal 8 version on any configuration tested. Note that absence of a background image is a recurring issue on the Drupal 8 site. 
 Steps to reproduce
1.	Go to the BCYF Mirabella Pool page

Desired Result
The background photo at the top of the page on D7 is present on D8 as well.

Actual Result The photo is missing on D8, and there is only whitespace in the background.

![2019 08 20 BCYF Mirabella Pool missing background image](https://user-images.githubusercontent.com/49662945/63362843-7df45a80-c340-11e9-8f7d-e4604dc25c69.jpg)

**Comment by taylor-iterators** [comment]
This is now rolled into issue #66

**Comment by mmcgowanBOS** [comment]
Seems to be fixed on staging.

**Comment by ollie-iterators** [comment]
This issue is closed
