### ISSUE TITLE
EMS Special Permit page lacking Suggested Content

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#63]
Screengrab/videos (insert file names here)
2019 08 20 EMS Special Permit page lacking Suggested Content.mp4

Link
http://bostond8stg.prod.acquia-sites.com/emergency-medical-services/how-apply-ems-special-event-permit

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
How To Apply For An EMS Special Event Permit > Body > Suggested Content

Brief Description
The bottom of the Drupal 7 version of the “How To Apply For An EMS Special Event Permit” page features a “Suggested Content” section. This section is entirely absent from the Drupal 8 version.
 Steps to reproduce
1.	Go to EMS How To Apply… page on Drupal 7
2.	Scroll down to the bottom, note that the last section is “Suggested Content”
3.	Attempt to do the same on Drupal 8 page

Desired Result
Suggested Content appears at the bottom of, or failing that, somewhere else on the page.

Actual Result
Suggested Content is found nowhere on the page.

[2019 08 20 EMS page lacking Suggested Content.zip](https://github.com/CityOfBoston/Iterators/files/3521826/2019.08.20.EMS.page.lacking.Suggested.Content.zip)

**Comment by mmcgowanBOS** [comment]
This is a repeat issue. Please see #76 .
