### ISSUE TITLE
EMS How To Apply page- limited contact info

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#64]
Screengrab/videos (insert file names here)
2019 08 20 EMS How To Apply page- limited contact info.png

Link
http://bostond8stg.prod.acquia-sites.com/emergency-medical-services/how-apply-ems-special-event-permit
http://bostond8stg.prod.acquia-sites.com/node/3621

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
How To Apply For An EMS Special Event Permit > Info column > Contact

Brief Description
A major component of the How To Apply… page is an ordered list, beginning with “Before You Apply Online.” To the right of it is a column with assorted relevant information; at the bottom of that column is the word “Contact:”, followed on the Drupal 7 site by a link to the EMS main page, then an emergency phone number, an email, and a physical address. On Drupal 8, of these there is only the EMS link.
 Steps to reproduce
1.	Go to EMS How To Apply… page
2.	Scroll down to “Contact:”, right next to “After We Get Your Application”
Desired Result
All of the links, reference information available there on Drupal 7 is available there on Drupal 8 as well.

Actual Result
Of the four lines of relevant information in D7, D8 only has the EMS link. 

- Note (8/30/19): The Drupal 8 page now has the other links, but now the link for the phone number only has the text for the phone number and does not have '(FOR EMERGENCIES, CALL OR TEXT 9-1-1)'

<img width="2554" alt="2019 08 20 EMS How To Apply page- limited contact info" src="https://user-images.githubusercontent.com/49662945/63370447-34ac0700-c350-11e9-8b9d-813c01178a7a.png">

**Comment by jimafisk** [comment]
One of the issues here is the URLs are different from D7 to D8 (note D7 has `/departments`):
- D7: https://bos-d7.lndo.site:3443/departments/emergency-medical-services/how-apply-ems-special-event-permit
- D8: https://boston.lndo.site:3443/emergency-medical-services/how-apply-ems-special-event-permit

@davidrkupton do you have thoughts on that ^

The other issue of missing contact info appears to be related to having the wrong view-mode for `field_contact` which should be rendered entity as Article. I believe this was updated with a previous PR.

**Comment by ollie-iterators** [comment]
The phone number link is missing '(FOR EMERGENCIES, CALL OR TEXT 9-1-1)'
