### ISSUE TITLE
Person page on Dupral 8 site missing Age Strong Leadership Team Content

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#65]
Screengrab/videos (insert file names here)
2019, 08, 20, Person page on Dupral 8 site missing Age Strong Leadership Team Content
[2019, 08, 20, Person page on Dupral 8 site missing Age Strong Leadership Team Content.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3521931/2019.08.20.Person.page.on.Dupral.8.site.missing.Age.Strong.Leadership.Team.Content.MP4.zip)
.mp4

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/27636 

Dupral 7 Link:
•	https://boston.gov/node/27636 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Internet Explorer 11.295.18362

Section
(Page > Area > Element)
Person page > Age strong leadership team > Content

Brief Description
Age strong leadership team content is not visible on the Dupral 8 page

Steps to reproduce
1. Go to the Dupral 7 and Dupral 8 page for node 27636
2. Check out the Age strong leadership team section on both pages

Desired Result
•	The Age strong leadership team content is on both pages

Actual Result
•	The Age strong leadership team content is not on Dupral 8

**Comment by davidrkupton** [comment]
This is related to there being no published people profiles.
