### ISSUE TITLE
Recurring Broken Header Images Bug

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#66]
Screengrab/videos (insert file names here)
2019 08 20 Recurring Broken Header Images Bug.mp4

Link
http://bostond8stg.prod.acquia-sites.com/emergency-medical-services/how-apply-ems-special-event-permit

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Various > Just below header > Background image

Brief Description
Most of the pages that have background images at the top of them in Drupal 7 do not have those images in Drupal 8; there is either white space or baby blue space in their place. This has been observed on the following pages so far:
http://bostond8stg.prod.acquia-sites.com/emergency-medical-services/how-apply-ems-special-event-permit
http://bostond8stg.prod.acquia-sites.com/understanding-plastic-bag-ordinance
http://bostond8stg.prod.acquia-sites.com/news/mayor-walsh-announces-office-immigrant-advancement
http://bostond8stg.prod.acquia-sites.com/news/mayor-walsh-opens-nominations-spark-bostons-annual-impact-awards
http://bostond8stg.prod.acquia-sites.com/innovation-and-technology/cityscore
http://bostond8stg.prod.acquia-sites.com/community-centers/bcyf-mirabella-pool
Note: The last of these was previously reported as its own bug, “BCYF Mirabella Pool missing background image” (number 60).

 Steps to reproduce
1.	Go to a page on Drupal 7 that has a background image at the top
2.	Go to the same page on Drupal 8

Desired Result
Background images appear consistently on each CMS.

Actual Result
Drupal 8 pages have blue or whitespace where those images ought to be.

[2019 08 20 Recurring Broken Header Images Bug.zip](https://github.com/CityOfBoston/Iterators/files/3521995/2019.08.20.Recurring.Broken.Header.Images.Bug.zip)

**Comment by mmcgowanBOS** [comment]
This seems to be fixed and is up on staging.

**Comment by ollie-iterators** [comment]
This is closed
