### ISSUE TITLE
6xxxxx nodes lead to Error 403

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#68]
Link
http://bostond8stg.prod.acquia-sites.com/node/63666

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Various

Brief Description
Nodes 63666, 63036, 64966, and 63086 prompt 403 errors (note: there is only one other 6XXXXX node in the testing spreadsheet provided, namely 61556, and it does not have an error like this)

 Steps to reproduce
1.	Go to one of the node links described above on Drupal 8

Desired Result
Page loads without incident.

Actual Result
User is met with an Error 403 Access Denied.

**Comment by reillyzlab** [comment]
Closing because resolved.
