### ISSUE TITLE
State value returned, not in validation CSV-flagging data discrepancy 

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#7]
Screengrab/videos (insert file names here)
2019 07 29, Address Return Value does not agree with validation source.mp4
[2019 07 29, Address Return Value does not agree with validation source.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3443680/2019.07.29.Address.Return.Value.does.not.agree.with.validation.source.mp4.zip)

Link
https://permit-finder.digital-staging.boston.gov/permit?id=ASB826319

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 75

Section
(Page > Area > Element)
Permit Info Page > About This Permit > Address

Brief Description
The Address info has the state the place is in on the staging site, while it is not present in the validation data that was given to check the information on the staging site

Steps to reproduce
1. Go to https://permit-finder.digital-staging.boston.gov/
2. Enter a valid permit
3. Press return

Desired Result
• All the information on the permit page matches the info in the validation document

Actual Result
• The information on the validation document for the address does not have the state in the address
o	This is clearly a desired result, but as it represents a difference we’re flagging it.

**Comment by TomM-IT** [comment]
We cross checked this in Prod, one thought was it may be a residual contact tag that did not get cleared out.

Tom

**Comment by paylakatel** [comment]
Thank you for flagging! We're okay with this one.
