### ISSUE TITLE
My Brother's Keeper differences from Drupal 7

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#70]
Screengrab/videos (insert file names here)
2019 08 20 My Brother's Keeper differences from Drupal 7.mp4

Link
http://bostond8stg.prod.acquia-sites.com/civic-engagement/my-brothers-keeper-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
My Brother’s Keeper Boston > Various

Brief Description
The following are ways the Drupal 8 page differs from the Drupal 7 page; note that some differences are not addressed as they are covered by other bug reports (e.g. lack of background photo w/ Obama) (accompanied by time stamps for attached video):
1.	Above “About The Program”, D7 has a descriptive paragraph; D8 instead rehashes the list both CMSs place under About The Program (0:05)
2.	D8 includes “My Brother’s Keeper Boston is led by Executive Director William Onuoha”, absent from D7 (0:03)
3.	“Watch: Award Winner…” background photo is absent from D8 (0:12)
4.	“Mini Grants Program”, “Mini Grants Recipients”, and “Advisory Board” are all present in D8, absent in D7 (0:18)
5.	“Board Members”, “Meet the Leadership” have fully-functional individual profiles on D7, but contain no content on D8 (0:27)
6.	“Who’s Involved” section does not exist on D8 (0:23)

Desired Result
Content visible on D8 site closely mirrors that visible on D7 site.

Actual Result
The two My Brother’s Keeper builds look significantly different, and the Drupal 8 page is missing what seems to be important content.

[2019 08 20 My Brother's Keeper differences from Drupal 7.zip](https://github.com/CityOfBoston/Iterators/files/3522334/2019.08.20.My.Brother.s.Keeper.differences.from.Drupal.7.zip)

**Comment by davidrkupton** [comment]
Fixed the RH column issue.
Body copy revsision issue fixed with update to fixRevisions in MigrationFixes().

**Comment by davidrkupton** [comment]
Need to add the Who's involved (contacts) view at the bottom of the page.

**Comment by davidrkupton** [comment]
Done.

**Comment by taylor-iterators** [comment]
The two pages are almost identical now; very close to being able to close this! The only concern I have at this point is that for the video embedded halfway down the page, the descriptive text is small and very dark, compared to the large, easily-legible white text used there on the Drupal 7 site.  See attached image.

<img width="2558" alt="2019 09 05 My Brother's Keeper text over video" src="https://user-images.githubusercontent.com/49662945/64357078-f9593b80-cfd1-11e9-89c1-1c243a0e2377.png">

**Comment by jimafisk** [comment]
The video title text style should be all set with https://github.com/CityOfBoston/boston.gov-d8/pull/670. I also noticed that the spacing was off for `grid_of_people` so I fixed that. I also adjusted the margins for the individual `person_profile` listings within the grid to look like D7.
