### ISSUE TITLE
Less buttons on Side Menu for Places on Dupral 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#71]
Screengrab/videos (insert file names here)
2019 08 21, Less buttons on Side Menu for Places on Dupral 8 page.mp4
[2019 08 21, Less buttons on Side Menu for Places on Dupral 8 page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3525808/2019.08.21.Less.buttons.on.Side.Menu.for.Places.on.Dupral.8.page.mp4.zip)

Link and Node #
Side Menu Module

Type of User:  Anonymous
 
Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Side Menu > Places > Buttons

Brief Description
There are less buttons on the Dupral 8 page for Places on the Side Menu than on the Dupral 7 page
 Steps to reproduce
1. Open the Dupral 7 and Dupral 8 pages
2. Go to the Side Menu on both pages and compare the buttons

Desired Result
• There are the same amount of buttons on both pages

Actual Result
• There is a different amount of buttons on the Dupral 8 page for Places than the Dupral 7 site
o  The missing buttons are ‘Cemeteries’ and ‘Neighborhoods’

**Comment by jimafisk** [comment]
The menu link content appears to be migrating over appropriately to the main_menu:

![menu](https://user-images.githubusercontent.com/5913244/63803123-29258680-c8e2-11e9-8a5d-5a25a8217c1a.png)

The actual nodes exist, but are throwing 403 errors for anonymous users:
- Cemeteries: https://boston.lndo.site:3443/node/33006
- Neighborhoods: https://boston.lndo.site:3443/node/33066

@davidrkupton based on our conversation this morning about forward revisions (drafts), I believe this is related to the work you're currently doing, correct?

**Comment by davidrkupton** [comment]
This is a migration issue.
Should now be fixed after next migration..

**Comment by ollie-iterators** [comment]
Now there are more buttons that are missing in the Places tab: ('Cemeteries', 'Community Centers', 'Neighborhoods' and 'Parks and Playgrounds') and the only buttons that work on the side bar now on the Drupal 8 page are the Places button and then Government buttons
[2019 09 11, Side Bar Bugs.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3601521/2019.09.11.Side.Bar.Bugs.mp4.zip)

**Comment by jimafisk** [comment]
This is all set on the latest dev: http://bostond8dev.prod.acquia-sites.com
