### ISSUE TITLE
Events Page Sections button causes the page to go downward so much the Section titles are not visible

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#73]
Screengrab/videos (insert file names here)
2019 08 21, Events Page Sections button causes the page to go downward so much the Section titles are not visible
[2019 08 21, Events Page Sections goes downward so much the Section titles are not visible.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3526057/2019.08.21.Events.Page.Sections.goes.downward.so.much.the.Section.titles.are.not.visible.mp4.zip)
.mp4

Link and Node #
Dupral 8 Link:
• http://bostond8stg.prod.acquia-sites.com/node/45351 

Dupral 7 Link:
• https://boston.gov/node/45351 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Samsung Galaxy S8 > Android 8.0.0 > Chrome 76

Section
(Page > Area > Element)
Event page > Page Sections > Buttons

Brief Description
Event Page Sections buttons cause the page to go downward so much the Section titles are not visible on the Dupral 8 page
 Steps to reproduce
1. Open the Dupral 7 and Dupral 8 page for node 45351
2. Go to the Page Sections area
3. Click to go to the various sections and see how the two pages behave differently

Desired Result
• The pages do not go downward enough that the section titles are not visible on the screen

Actual Result
• The pages go downward enough that the section titles are not visible on the screen
o  Note: This does not happen with the Helpful Resources section, but this is because the Helpful Resources section is the lowest section

**Comment by davidrkupton** [comment]
Cant replicate this on chrome in phone-mode on my computer.
I did some work on the scroller, can you re-test this and see if it is still an issue ?
Thanks.

**Comment by ollie-iterators** [comment]
Fixed
