### ISSUE TITLE
Suggested Content missing from Personal Tax Abatement page

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#76]
Screengrab/videos (insert file names here)
2019 Suggested Content missing from Personal Tax Abatement page.mp4

Link
http://bostond8stg.prod.acquia-sites.com/assessing/how-file-personal-property-tax-abatement

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Chrome 76

Section
(Page > Area > Element)
How to file for a personal property tax abatement > Body > Suggested Content

Brief Description
The Drupal 7 version of the “How to file for a personal property tax abatement” page ends with a “Suggested Content” section, containing several links. The section is entirely absent from the Drupal 8 build.
 Steps to reproduce
1.	Go to the “How to file for a personal property tax abatement” page on both Drupal 7 and 8 builds
2.	Scroll down to the bottom of each

Desired Result
Both versions of the page have “Suggested Content.”

Actual Result Suggested Content is not present on Drupal 8 page.

[2019 Suggested Content missing from Personal Tax Abatement page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3526619/2019.Suggested.Content.missing.from.Personal.Tax.Abatement.page.mp4.zip)

**Comment by mmcgowanBOS** [comment]
This content is something we are planning to migrate after the d8 launch. I'm going to close for now as we were aware of this before testing with Iterators even began.
