### ISSUE TITLE
Contact Us form on Events page gives multiple error messages when Send Message button is pressed multiple times

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#78]
Screengrab/videos (insert file names here)
2019 08 22, Contact Us form on Events page gives multiple error messages when Send Message button is pressed multiple times
[2019 08 22, Contact Us form on Events page gives multiple error messages when Send Message button is pressed multiple times.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3530669/2019.08.22.Contact.Us.form.on.Events.page.gives.multiple.error.messages.when.Send.Message.button.is.pressed.multiple.times.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/13166 

Dupral 7 Link:
•	https://boston.gov/node/13166 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Tablet > Galaxy Tablet A > Android 6.0.1

Section
(Page > Area > Element)
Events page > Contact Us Form > Error messages

Brief Description
The Contact Us form on Events gives multiple error messages when the Send Message button is clicked Multiple times

Steps to reproduce
1. Go to the Dupral 7 and 8 pages for node 13166
2. 00:11 Go down to the event information and click on the email address
3. 00:12 Click the ‘Send Message’ button multiple times without entering any values into the text fields. Multiple error messages show up on the page after clicking multiple times on the 'Send Message' button

Desired Result
•	Only one error message shows up, not multiple

Actual Result
•	One error message shows up for each press of the ‘Send Message’ button

**Comment by davidrkupton** [comment]
This is a bug in the patterns javascript (/scripts/components/contct.js) compiled into in all.js.
This issue exists in D7, so we will fix in due course, but should not block ATM.

**Comment by ollie-iterators** [comment]
This doesn't appear to be fixed right now. Please advise.

**Comment by subaha-cob** [comment]
Fixed. See previous comments.

**Comment by subaha-cob** [comment]
Testing at: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
I'm not seeing a contact us form on the node is question

**Comment by ollie-iterators** [comment]
@andrebtlima , The contact us form shows up after clicking on the email address: "PUBLICWORKS@BOSTON.GOV" on the website. I have reviewed the bug today, on the UAT page and have found that the issue of multiple error messages showing up after clicking on the Submit button for the Contact Us Form has been fixed. This bug can be closed.
