### ISSUE TITLE
The Translate button is not working on the pages

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#79]
Screengrab/videos (insert file names here)
2019 08 27, Translate not working on page.mp4
[2019 08 27, Translate not working on page.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3547305/2019.08.27.Translate.not.working.on.page.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/

Dupral 7 Link:
•	https://www.boston.gov/

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Chrome 76

Section
(Page > Area > Element)
Page > Header > Translate button

Brief Description
The translate button does not work on the pages

Steps to reproduce
1. Go to the boston.gov and bostond8stg.prod.acquia-sites.com
2. Click on the Translate button
3. Click on any of the languages

Desired Result
•	The language for the page changes to the other language that was clicked on

Actual Result
•	Nothing happens on the page

**Comment by mmcgowanBOS** [comment]
Yes. this is a known issue on both d7 and d8. I'm going to close for now knowing this will be a greater dev project once we launch the site.
