### ISSUE TITLE
Footer is not visible

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#8]
Screengrab/videos (insert file names here)
Footer is not visible, Mac Safari and Chrome.mp4
Footer is not visible, Mac Safari and Chrome.png

Link
https://permit-finder.digital-staging.boston.gov/ 

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.5 > Safari 12.1.2 or Chrome 75.0.3770.142 (Official Build) (64-bit)

Section
(Page > Area > Element)
Permit Finder > Footer > Footer

Brief Description
The footer is displayed off-screen and the window has a scroll bar even though there is enough room to display the footer.

Steps to reproduce
1.  0:00 (time refers to the video)  Observe that the footer is not displayed and a vertical scroll bar is present even though there is enough white space, as shown in the steps below.
2.  0:02, scroll to see the footer
3.  0:05 decrease the window height and the footer moves too given that there is plenty of white space to move into
4.  0:09, the white space has run out, so the footer is again scrolled off screen
5.  0:10, increasing the screen height brings the footer back into display
6.  0:14, scroll the window so that the footer is only partially visible in order to see the bug listed below.
7.  0:15, decrease and increase the window height---- Bug:  The footer is always partially off screen and the scroll bar remains not matter how tall the window is made.

Desired Result
Footer is displayed when the window is tall enough.

Actual Result
Footer is off-screen and a vertical scroll bar are shown.

The following is a screen capture
![Footer is not visible, Mac Safari and Chrome](https://user-images.githubusercontent.com/33845414/62091680-2599d380-b240-11e9-9137-709a2bb5c3db.png)

The following is a movie converted to a zip file.
[Footer is not visible, Mac Safari and Chrome.zip](https://github.com/CityOfBoston/Iterators/files/3444691/Footer.is.not.visible.Mac.Safari.and.Chrome.zip)

**Comment by reillyzlab** [comment]
Probably don't need if moving into boston.gov
