### ISSUE TITLE
City Council pages missing Committee Involvement

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#81]
Screengrab/videos (insert file names here)
City Council pages missing Committee Involvement.png

Link
http://bostond8stg.prod.acquia-sites.com/city-council/mark-ciommo

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Chrome 76.0.3809.100

Section
(Page > Area > Element)
Mark Ciommo personal page > Body > Committee Involvement section

Brief Description
At this point the Drupal 8 version of this page, as with every other City Council personal page, looks very similar to its Drupal 7 counterpart. However, these pages are all missing the “Committee Involvement” section, which on the D7 pages can be found just above “Wards and Precincts.”
 Steps to reproduce
1.	Go to Mark Ciommo’s page on both production and staging sites
2.	Scroll down to the bottom of the page

Desired Result
The two pages display all the same sections, containing comparable content.

Actual Result
“Committee Involvement” is entirely absent from the D8 page.

<img width="2558" alt="City Council pages missing Committe Involvement" src="https://user-images.githubusercontent.com/49662945/64349657-513d7580-cfc5-11e9-813d-be59e19b82b6.png">

**Comment by jimafisk** [comment]
Appears to be fixed on latest dev: http://bostond8stg.prod.acquia-sites.com/departments/city-council/mark-ciommo

![Screenshot_2019-09-23 Mark Ciommo](https://user-images.githubusercontent.com/5913244/65457769-4e8ead00-de1a-11e9-946e-96f90f4930bd.png)
