### ISSUE TITLE
Winter in Boston broken links

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#83]
Screengrab/videos (insert file names here)
Winter in Boston broken links.mp4

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Body > Various

Brief Description
The following links within the “Winter in Boston” page generate 404 Not Found errors (“Looks like this page went overboard…”):
1.	“List of discounted parking garages” (in Parking Bans section)
2.	“Learn more about towing in Boston” (in Towed Cars section)
3.	“What you can expect to find” and “Rules on Clearing Snow” (in Shoveling section)
4.	“More Important Numbers” (in If You Lose Power section)
 Steps to reproduce
1.	Go to Winter in Boston page
2.	Scroll down to Parking Bans section and click on “List of discounted parking garages” (0:04 in recording)
3.	Return to WiB page, scroll down to Towed Cars, and click “Learn more about towing in Boston (0:12)
4.	Return to WiB page, scroll down to Shoveling, and click “What you can expect to find” and “Rules on Clearing Snow” (0:23)
5.	Return to WiB page, scroll down to If You Lose Power, and click “More Important Numbers” (0:36)

Desired Result
All links open to appropriate pages.

Actual Result
All links lead to 404 page.

**Comment by jimafisk** [comment]
This seems to be working now, closing.

cc @mmcgowanBOS
