### ISSUE TITLE
Winter in Boston missing images

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#87]
Screengrab/videos (insert file names here)
Winter in Boston missing images- Plowing.png
Winter in Boston missing images- Snow Day Drop-In Program.png

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Body > Multiple background images

Brief Description
The Drupal 7 version of the Winter in Boston page includes two background images that are entirely absent from the Drupal 8 site.
 Steps to reproduce
1.	Go to Winter in Boston page on the Drupal 7 site
2.	Scroll down to the Plowing section
3.	Scroll down further to the Help Paying For Fuel. Note that surrounding these two sections, there are large background images.
4.	Repeat the above steps on Drupal 8

Desired Result
Background images are present on D8 site.

Actual Result
D8 site has white space where images should be.

<img width="2558" alt="Winter in Boston missing images- Plowing" src="https://user-images.githubusercontent.com/49662945/64808956-430fcc00-d566-11e9-8572-d03cc8aaed5f.png">
<img width="2560" alt="Winter in Boston missing images- Snow Day Drop-In Program" src="https://user-images.githubusercontent.com/49662945/64808957-430fcc00-d566-11e9-9799-e9ed90c74c88.png">

**Comment by ollie-iterators** [comment]
This is also happening on the page: http://bostond8stg.prod.acquia-sites.com/departments/environment/resilient-boston-harbor

[2019 09 16, Resilient Boston Harbor Image Errors.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3616620/2019.09.16.Resilient.Boston.Harbor.Image.Errors.MP4.zip)

**Comment by reillyzlab** [comment]
Fixed.
