### ISSUE TITLE
There is a content collision between the header and the content next to the header on the Neighborhood Coffee Hours page on the Drupal 8 site

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#88]
Screengrab/videos (insert file names here)
2019 09 12, Content Collision on Neighborhood Coffee Hours Page.mp4
[2019 09 12, Content Collision on Neighborhood Coffee Hours Page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3606861/2019.09.12.Content.Collision.on.Neighborhood.Coffee.Hours.Page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/departments/parks-and-recreation/neighborhood-coffee-hours

Dupral 7 Link:
•	https://www.boston.gov/departments/parks-and-recreation/neighborhood-coffee-hours

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Neighborhood Coffee Hours Page > Header > Content Collision

Brief Description
There is a content collision between the header and the content next to the header on the Neighborhood Coffee Hours page on the Drupal 8 site

Steps to reproduce
1. Go to the Neighborhood Coffee Hours page for Drupal 8
2. Make the page smaller / larger until the header collides with text next to it

Desired Result
•	The header does not collide with content

Actual Result
•	The header collides with content

**Comment by reillyzlab** [comment]
Closing because resolved.
