### ISSUE TITLE
City Emblem Disappears With Screen Magnification

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#9]
Screengrab/videos (insert file names here)
City Emblem Disappears With Screen Magnification.mp4

Link
https://permit-finder.digital-staging.boston.gov/

 Environment
(Device > OS > Browser)
Desktop > Mac OS 10.14.6 > Chrome 75.0.3770.142, Firefox 68.0, Safari 12.1.2, Edge 77.0.230.0 

Section
(Page > Area > Element)
Permit Finder > Header > City of Boston Emblem
[City Emblem Disappears With Screen Magnification.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3447232/City.Emblem.Disappears.With.Screen.Magnification.mp4.zip)

Brief Description
When the user magnifies the screen, beyond a certain point the City emblem disappears; this does not significantly hinder the functionality of the page. This happens around 240% magnification on Chrome and Firefox, but 200% on Microsoft Edge.
 Steps to reproduce
1. Go to the Permit Finder (staging) site, keeping the header in view
2. Use CMD + to magnify the screen several times

Desired Result
Each magnification affects all page components in equal measure, and all content remains displayed at any size.

Actual Result
Beyond a certain point the emblem ceases to be displayed.

**Comment by reillyzlab** [comment]
Probably don't need if moving into boston.gov

**Comment by subaha-cob** [comment]
This is not a bug because it is functioning as it should.
