### ISSUE TITLE
Winter in Boston- daily status missing

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#90]
Screengrab/videos (insert file names here)
Winter in Boston- daily status missing.png

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Daily status section

Brief Description
On Drupal 7, very near the top of the Winter in Boston page is a header with today’s date, followed by various pieces of information about practical affairs in the city on this day. It is entirely absent from the Drupal 8 site.
 Steps to reproduce
1.	Go to Winter in Boston page on Drupal 7
2.	Scroll down to today’s date and associated information
3.	Attempt to do the same on Drupal 8 page

Desired Result
The daily status content is visible on D8 as in D7.

Actual Result
The daily status content is missing from D8.

<img width="2560" alt="Winter in Boston- daily status missing" src="https://user-images.githubusercontent.com/49662945/64813014-63dc1f80-d56e-11e9-8b81-305839b4df1f.png">

**Comment by mmcgowanBOS** [comment]
This a content / layout option that only should show if we want it, and in specific circumstances. The Drupal 8 staging site doesn't show it for now. I don't see this as an issue. Closing for now.
