### ISSUE TITLE
Broken How-to tabs and Missing How-to Contact Step

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/Iterators#91]
Screengrab/videos (insert file names here)
How To Get A Resdient Parking Permit- icon-time bar.mp4

Link
http://bostond8stg.prod.acquia-sites.com/parking-clerk/how-get-resident-parking-permit#replace-your-permit

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
How To Get A Resident Parking Permit > Replace Your Permit > above Proof of Boston Residency

Brief Description
If the user selects the “Replace Your Permit” option on the How To Get A Resident Parking Permit page, then scrolls down to between the bottom of the three-step list and the “Proof of Boston Residency” section, he sees a prominent black horizontal bar containing the plain text “icon-time.” All this is only visible when Replace Your Permit is chosen, and there is no equivalent on the Drupal 7 version.
 Steps to reproduce
1.	Go to How To Get A Resident Parking Permit page on Drupal 7
2.	Select Replace Your Permit
3.	Scroll down to just under the bottom of the three-step list
4.	Repeat this process on Drupal 8

Desired Result
The content shown on D8 is the same as that on D7.

Actual Result
A large black bar containing improper-looking text is seen on D8, and not D7.

[How To Get A Resdient Parking Permit- icon-time bar.zip](https://github.com/CityOfBoston/Iterators/files/3607171/How.To.Get.A.Resdient.Parking.Permit-.icon-time.bar.zip)

**Comment by jimafisk** [comment]
Here's the D7 link: https://www.boston.gov/departments/parking-clerk/how-get-resident-parking-permit

I notice a couple of issues. First, the tabs do not look correct:

<details>
<summary>Tabs on D7</summary>

![tabs_d7](https://user-images.githubusercontent.com/5913244/65537692-b0f7b400-ded3-11e9-99ef-e0244b6a2ee6.png)

</details>
<details>
<summary>Tabs on D8</summary>

![broken_tabs](https://user-images.githubusercontent.com/5913244/65537701-b654fe80-ded3-11e9-962d-0fb3c29f5e8d.png)

</details>

Further down the page on D8 there is a broken component:
<details>
<summary>No bar on D7</summary>

![bar_d7](https://user-images.githubusercontent.com/5913244/65537720-c10f9380-ded3-11e9-9a1b-13193df1adf5.png)

</details>
<details>
<summary>Bar on D8</summary>

![bar](https://user-images.githubusercontent.com/5913244/65537752-d389cd00-ded3-11e9-8825-4cf751e87613.png)


</details>

**Comment by jimafisk** [comment]
Thank goodness for Firefox's (superior) dev tools, they helped me find the [white space text nodes](https://blog.nightly.mozilla.org/2016/10/17/devtools-now-display-white-space-text-nodes-in-the-dom-inspector/) that were throwing the tab displays off:

![white-space-only-text-node](https://user-images.githubusercontent.com/5913244/65543492-3df43a80-dedf-11e9-81a9-8fabd861508d.png)

To fix this, I deleted the closing `</li>` in the for loop since it seemed like the cleanest fix listed here: https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by jimafisk** [comment]
I've got the dates displaying now:

![dates](https://user-images.githubusercontent.com/5913244/65705498-913cc900-e056-11e9-80f6-1b5188af2fb7.png)

But I've discovered a couple of issues with addresses:

<details>
<summary>Data is not migrating from D7 to D8</summary>

D7:

![address_d7](https://user-images.githubusercontent.com/5913244/65705575-b7626900-e056-11e9-82ff-123b8feeb918.png)

D8:

![address_empty](https://user-images.githubusercontent.com/5913244/65705585-bcbfb380-e056-11e9-8c37-ab829a217a8d.png)

</details>
<details>
<summary>There are extra required fields that should be removed</summary>

![extra_address_fields](https://user-images.githubusercontent.com/5913244/65705609-cc3efc80-e056-11e9-8245-fc4acd25fcb7.png)


</details>
