### ISSUE TITLE
The Recycle Right section has no image on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#93]
Screengrab/videos (insert file names here)
2019 09 13, Recycle Right section has no image on Drupal 8 page.mp4
[2019 09 13, Recycle Right section has no image on Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610468/2019.09.13.Recycle.Right.section.has.no.image.on.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Recycle Right > Image

Brief Description
The Recycle Right section has no image on the Drupal 8 page

Steps to reproduce
1. Open the Drupal 7 and 8 page for Trash and Recycling Guide
2. Go down to the Recycle Right section

Desired Result
•	Both pages have an image for the Recycle Right section

Actual Result
•	The Drupal 8 page has no image for the Recycle Right section

**Comment by reillyzlab** [comment]
resolved so closing
