### ISSUE TITLE
The Hazardous Waste Drop-Offs section is missing all its content on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#95]
Screengrab/videos (insert file names here)
2019 09 13, Hazardous Waste Drop-Offs missing content in Drupal 8 page.mp4
[2019 09 13, Hazardous Waste Drop-Offs missing content in Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610561/2019.09.13.Hazardous.Waste.Drop-Offs.missing.content.in.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Hazardous Waste Drop-Offs > Content

Brief Description
The Hazardous Waste Drop-Offs section is missing all its content on the Drupal 8 page

Steps to reproduce
1. Go to the Rash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the Hazardous Waste Drop-Offs section 

Desired Result
•	Both sections have the proper content for the section

Actual Result
•	The Hazardous Waste Drop-Offs section for the Drupal 8 page has no content

**Comment by reillyzlab** [comment]
Resolved so closing
