### ISSUE TITLE
The Food Access button is missing its image on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#96]
Screengrab/videos (insert file names here)
2019 09 13, Food Access button missing image in Drupal 8 page.mp4
[2019 09 13, Food Access button missing image in Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610573/2019.09.13.Food.Access.button.missing.image.in.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Food Access button > Image

Brief Description
The Food Access button is missing its image on the Drupal 8 page

Steps to reproduce
1. Go to the Rash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the Food Access button 

Desired Result
•	Both buttons have the proper image on the page

Actual Result
•	The Food Access button is missing its image on the Drupal 8 page

**Comment by reillyzlab** [comment]
Resolved so closing
