### ISSUE TITLE
The Composting tips button in the Composting in the City section is missing its header on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#97]
Screengrab/videos (insert file names here)
2019 09 13, Button in Composting in the City section missing header in Drupal 8 page.mp4
[2019 09 13, Button in Composting in the City section missing header in Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610588/2019.09.13.Button.in.Composting.in.the.City.section.missing.header.in.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Composting in the City section > Composting Tips button

Brief Description
The Composting tips button in the Composting in the City section is missing its header on the Drupal 8 page

Steps to reproduce
1. Go to the Rash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the Composting in the City section 

Desired Result
•	Both buttons have the proper content on the page

Actual Result
•	The Composting Tips button is missing its header on the Drupal 8 page

**Comment by reillyzlab** [comment]
Resolved so closing
